<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="João Pavão">
<meta name="dcterms.date" content="2026-09-14">

<title>1&nbsp; Classical Cryptography — Substitution, Polyalphabetic and Transposition Ciphers – Cryptography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/cap02.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-9a023c9ade86a60361e96e3e3f11bc54.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-61bc4ac84974e0785b3107ee93e74bfb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bc9f1d3aef906c45e091843ae87821a0.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/cap01.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Classical Cryptography — Substitution, Polyalphabetic and Transposition Ciphers</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Cryptography</a> 
        <div class="sidebar-tools-main">
    <a href="../../index.html" title="Versão portuguesa" class="quarto-navigation-tool px-1" aria-label="Versão portuguesa"><i class="bi bi-translate"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap01.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Classical Cryptography — Substitution, Polyalphabetic and Transposition Ciphers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Block Ciphers — Fundamentals, Feistel, DES and 3DES</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">AES — Stages and Modes of Operation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stream Ciphers — RC4, Salsa20, ChaCha20 and Padding</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hashing — Properties, Attacks, SHA, MAC and HMAC</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Asymmetric Cryptography and RSA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Diffie-Hellman and Digital Signatures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Elliptic Curve Cryptography</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Public Key Infrastructure (PKI)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">TLS and PGP</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/cap11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Algorithmic Efficiency and Post-Quantum Cryptography</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-01-intro" id="toc-sec-01-intro" class="nav-link active" data-scroll-target="#sec-01-intro">Introduction</a></li>
  <li><a href="#sec-01-fundamentos" id="toc-sec-01-fundamentos" class="nav-link" data-scroll-target="#sec-01-fundamentos"><span class="header-section-number">1.1</span> Fundamentals of Cryptographic Systems</a>
  <ul class="collapse">
  <li><a href="#sec-01-classificacao" id="toc-sec-01-classificacao" class="nav-link" data-scroll-target="#sec-01-classificacao"><span class="header-section-number">1.1.1</span> Classifying cryptographic systems</a></li>
  <li><a href="#sec-01-modelo" id="toc-sec-01-modelo" class="nav-link" data-scroll-target="#sec-01-modelo"><span class="header-section-number">1.1.2</span> The symmetric cipher model</a></li>
  <li><a href="#sec-01-kerckhoffs" id="toc-sec-01-kerckhoffs" class="nav-link" data-scroll-target="#sec-01-kerckhoffs"><span class="header-section-number">1.1.3</span> Kerckhoffs’s principle</a></li>
  <li><a href="#sec-01-ataques" id="toc-sec-01-ataques" class="nav-link" data-scroll-target="#sec-01-ataques"><span class="header-section-number">1.1.4</span> Brute force and cryptanalysis</a></li>
  </ul></li>
  <li><a href="#sec-01-substituicao" id="toc-sec-01-substituicao" class="nav-link" data-scroll-target="#sec-01-substituicao"><span class="header-section-number">1.2</span> Substitution Ciphers</a>
  <ul class="collapse">
  <li><a href="#sec-01-cesar" id="toc-sec-01-cesar" class="nav-link" data-scroll-target="#sec-01-cesar"><span class="header-section-number">1.2.1</span> The Caesar cipher</a></li>
  <li><a href="#sec-01-monoalfabetica" id="toc-sec-01-monoalfabetica" class="nav-link" data-scroll-target="#sec-01-monoalfabetica"><span class="header-section-number">1.2.2</span> The monoalphabetic cipher</a></li>
  <li><a href="#sec-01-playfair" id="toc-sec-01-playfair" class="nav-link" data-scroll-target="#sec-01-playfair"><span class="header-section-number">1.2.3</span> The Playfair cipher</a></li>
  <li><a href="#sec-01-vigenere" id="toc-sec-01-vigenere" class="nav-link" data-scroll-target="#sec-01-vigenere"><span class="header-section-number">1.2.4</span> Polyalphabetic cipher: Vigenère</a></li>
  <li><a href="#sec-01-vernam" id="toc-sec-01-vernam" class="nav-link" data-scroll-target="#sec-01-vernam"><span class="header-section-number">1.2.5</span> The Vernam cipher</a></li>
  <li><a href="#sec-01-otp" id="toc-sec-01-otp" class="nav-link" data-scroll-target="#sec-01-otp"><span class="header-section-number">1.2.6</span> The One-Time Pad</a></li>
  <li><a href="#sec-01-enigma" id="toc-sec-01-enigma" class="nav-link" data-scroll-target="#sec-01-enigma"><span class="header-section-number">1.2.7</span> The Enigma machine</a></li>
  </ul></li>
  <li><a href="#sec-01-transposicao" id="toc-sec-01-transposicao" class="nav-link" data-scroll-target="#sec-01-transposicao"><span class="header-section-number">1.3</span> Transposition Ciphers</a>
  <ul class="collapse">
  <li><a href="#sec-01-rail-fence" id="toc-sec-01-rail-fence" class="nav-link" data-scroll-target="#sec-01-rail-fence"><span class="header-section-number">1.3.1</span> The rail fence technique</a></li>
  <li><a href="#sec-01-transposicao-colunar" id="toc-sec-01-transposicao-colunar" class="nav-link" data-scroll-target="#sec-01-transposicao-colunar"><span class="header-section-number">1.3.2</span> Columnar transposition</a></li>
  </ul></li>
  <li><a href="#sec-01-sintese" id="toc-sec-01-sintese" class="nav-link" data-scroll-target="#sec-01-sintese"><span class="header-section-number">1.4</span> Chapter Summary</a></li>
  <li><a href="#sec-01-reflexao" id="toc-sec-01-reflexao" class="nav-link" data-scroll-target="#sec-01-reflexao"><span class="header-section-number">1.5</span> Discussion Question</a></li>
  <li><a href="#sec-01-referencias" id="toc-sec-01-referencias" class="nav-link" data-scroll-target="#sec-01-referencias">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Classical Cryptography — Substitution, Polyalphabetic and Transposition Ciphers</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>João Pavão </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">14 September 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="sec-01-intro" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-01-intro">Introduction</h2>
<p>Cryptography is the discipline that studies techniques for protecting information by transforming it into a form unreadable to anyone who does not possess the key needed to reverse that transformation. This chapter introduces the fundamental concepts that run through the entire discipline, the symmetric cipher model, Kerckhoffs’s principle, the distinction between brute force and cryptanalysis, and then works through the classical ciphers: substitution and transposition systems developed over centuries, well before the appearance of the computer.</p>
<p>These ciphers are, from the point of view of practical security, completely obsolete today, trivial to break with modern computational resources. Their value in this module is pedagogical: they introduce, in a simple and manual way, the concepts of key, key space, brute-force attack and cryptanalysis that apply, with exactly the same logic, to the modern systems studied in the following chapters.</p>
</section>
<section id="sec-01-fundamentos" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-01-fundamentos"><span class="header-section-number">1.1</span> Fundamentals of Cryptographic Systems</h2>
<section id="sec-01-classificacao" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="sec-01-classificacao"><span class="header-section-number">1.1.1</span> Classifying cryptographic systems</h3>
<p>Cryptographic systems are classified according to three independent criteria:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Criterion</th>
<th style="text-align: left;">Categories</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of keys</td>
<td style="text-align: left;"><strong>Symmetric</strong> (a single key, shared between sender and receiver) or <strong>asymmetric</strong> (two distinct keys, one public and one private)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Type of operation</td>
<td style="text-align: left;"><strong>Substitution</strong> (each symbol is replaced by another) or <strong>transposition</strong> (the symbols themselves stay the same, but their order is changed)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Text processing</td>
<td style="text-align: left;"><strong>Block cipher</strong> (the text is processed in fixed-size blocks) or <strong>stream cipher</strong> (the text is processed continuously, symbol by symbol)</td>
</tr>
</tbody>
</table>
<p>This chapter deals exclusively with <strong>symmetric</strong> systems, of the <strong>substitution</strong> or <strong>transposition</strong> kind. The following chapters introduce modern block and stream ciphers.</p>
</section>
<section id="sec-01-modelo" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="sec-01-modelo"><span class="header-section-number">1.1.2</span> The symmetric cipher model</h3>
<p>A symmetric cryptographic system is defined by five components <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<ul>
<li><strong>Plaintext</strong> (<span class="math inline">\(X\)</span>): the original message, still intelligible.</li>
<li><strong>Encryption algorithm</strong> (<span class="math inline">\(E\)</span>): the procedure that transforms plaintext into ciphertext, through successive substitutions and transformations.</li>
<li><strong>Secret key</strong> (<span class="math inline">\(K\)</span>): a value independent of the plaintext and of the algorithm, shared between sender and receiver over a secure channel. Different keys produce different results for the same plaintext and the same algorithm.</li>
<li><strong>Ciphertext</strong> (<span class="math inline">\(Y\)</span>): the result of encryption, apparently random and, at first sight, unintelligible.</li>
<li><strong>Decryption algorithm</strong> (<span class="math inline">\(D\)</span>): essentially the encryption algorithm run in reverse, which uses the same key <span class="math inline">\(K\)</span> to recover the plaintext from the ciphertext.</li>
</ul>
<p>Formally:</p>
<p><span class="math display">\[Y = E(K, X)\]</span> <span class="math display">\[X = D(K, Y)\]</span></p>
<div id="fig-01-modelo-simetrico" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-modelo-simetrico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-modelo-cifra-simetrica-en.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-modelo-simetrico-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: The symmetric cipher model: sender and receiver have previously shared the same secret key, over a secure channel. The encryption algorithm uses that key to transform plaintext into ciphertext; the decryption algorithm, using the same key, reverses the transformation.
</figcaption>
</figure>
</div>
<p>Sender and receiver must have obtained copies of the same secret key by some secure means, and kept it protected (<a href="#fig-01-modelo-simetrico" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>). If someone discovers the key and knows the algorithm, all communication encrypted with that key becomes readable.</p>
</section>
<section id="sec-01-kerckhoffs" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="sec-01-kerckhoffs"><span class="header-section-number">1.1.3</span> Kerckhoffs’s principle</h3>
<p>A fundamental assumption of all modern cryptography, already present in these classical ciphers, is <strong>Kerckhoffs’s principle</strong>, formulated in 1883 <span class="citation" data-cites="Kerckhoffs1883">(<a href="cap01.html#ref-Kerckhoffs1883" role="doc-biblioref">Kerckhoffs 1883</a>)</span>: the security of a cipher must depend solely on the secrecy of the key, never on the secrecy of the algorithm. It is always assumed that an attacker knows the encryption and decryption algorithm perfectly, only the key is unknown.</p>
<p>This convention has an important practical consequence: an algorithm whose security depends on remaining secret (<em>security through obscurity</em>) is not considered secure in serious cryptography, precisely because that condition is impossible to guarantee in the long run. The algorithms studied in this module are all public and widely scrutinised: their security rests entirely on the size and the secrecy of the key.</p>
</section>
<section id="sec-01-ataques" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="sec-01-ataques"><span class="header-section-number">1.1.4</span> Brute force and cryptanalysis</h3>
<p>An attacker who wants to recover the plaintext without knowing the key has two general strategies available:</p>
<ul>
<li><strong>Brute force</strong>: exhaustively test every possible key, until one is found that produces intelligible plaintext. On average, roughly half of the total key space must be tested to obtain a result.</li>
<li><strong>Cryptanalysis</strong>: exploit additional knowledge about parts of the system, such as already-known plaintext/ciphertext pairs, or statistical properties of the algorithm, to deduce the key without testing it exhaustively.</li>
</ul>
<p>Classical cryptanalysis of the ciphers studied in this chapter relies chiefly on <strong>frequency analysis</strong>: the statistical distribution of letters in a natural language is not uniform, and that asymmetry survives, in varying degrees, the encryption process.</p>
<p>Depending on the information available to the cryptanalyst, several types of attack are distinguished <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Type of attack</th>
<th style="text-align: left;">What the cryptanalyst knows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ciphertext only</td>
<td style="text-align: left;">The algorithm and the ciphertext</td>
</tr>
<tr class="even">
<td style="text-align: left;">Known plaintext</td>
<td style="text-align: left;">The algorithm, the ciphertext, and one or more plaintext/ciphertext pairs formed with the same key</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chosen plaintext</td>
<td style="text-align: left;">The algorithm, the ciphertext, and a plaintext chosen by the attacker, with the corresponding ciphertext</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chosen ciphertext</td>
<td style="text-align: left;">The algorithm, the ciphertext, and a ciphertext chosen by the attacker, with the corresponding decrypted plaintext</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chosen text</td>
<td style="text-align: left;">The combined knowledge of the two previous attacks</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-01-substituicao" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-01-substituicao"><span class="header-section-number">1.2</span> Substitution Ciphers</h2>
<p>In a substitution cipher, each symbol of the plaintext is <strong>replaced</strong> by another symbol, according to a fixed rule determined by the key. The order of the symbols stays unchanged; what changes is their identity.</p>
<section id="sec-01-cesar" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="sec-01-cesar"><span class="header-section-number">1.2.1</span> The Caesar cipher</h3>
<p>The Caesar cipher, attributed to Julius Caesar, is the simplest substitution cipher: each letter is replaced by the letter found <span class="math inline">\(k\)</span> positions further down the alphabet, with <span class="math inline">\(k\)</span> the key. For example, with <span class="math inline">\(k = 3\)</span>, encrypting the instruction “meet me under the bridge” <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<div class="httpmsg">
<pre><code>Plain:   M E E T   M E   U N D E R   T H E   B R I D G E
Cipher:  P H H W   P H   X Q G H U   W K H   E U L G J H</code></pre>
</div>
<p>Numbering the letters of the alphabet from 0 (A) to 25 (Z), the Caesar cipher is formally defined by:</p>
<p><span class="math display">\[C = E(k, p) = (p + k) \bmod 26\]</span> <span class="math display">\[p = D(k, C) = (C - k) \bmod 26\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
<th style="text-align: center;">J</th>
<th style="text-align: center;">K</th>
<th style="text-align: center;">L</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">O</th>
<th style="text-align: center;">P</th>
<th style="text-align: center;">Q</th>
<th style="text-align: center;">R</th>
<th style="text-align: center;">S</th>
<th style="text-align: center;">T</th>
<th style="text-align: center;">U</th>
<th style="text-align: center;">V</th>
<th style="text-align: center;">W</th>
<th style="text-align: center;">X</th>
<th style="text-align: center;">Y</th>
<th style="text-align: center;">Z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">25</td>
</tr>
</tbody>
</table>
<p>The modulo-26 operation guarantees that the result always stays within the valid range: when the sum exceeds 25, the remainder of division by 26 brings it back into the alphabet. For example, encrypting the letter “y” (<span class="math inline">\(p = 24\)</span>) with <span class="math inline">\(k = 3\)</span>: <span class="math inline">\(C = (24 + 3) \bmod 26 = 27 \bmod 26 = 1\)</span>, which corresponds to the letter “B”.</p>
<p><strong>Key space and brute force.</strong> The key <span class="math inline">\(k\)</span> can only take 25 distinct values (excluding <span class="math inline">\(k = 0\)</span>, which encrypts nothing, and <span class="math inline">\(k = 26\)</span>, equivalent to <span class="math inline">\(k = 0\)</span>). Such a small key space makes the Caesar cipher trivially vulnerable to a brute-force attack: simply generate all 25 candidate decryptions and identify the one that is intelligible.</p>
<p><strong>Cryptanalysis by frequency analysis.</strong> Even without resorting to brute force, the Caesar cipher is easily broken by cryptanalysis, by exploiting two sources of information: the structure of the text (spaces between words survive encryption, revealing the length of each word) and the language of the plaintext (allowing a search for patterns of short, frequent words, such as “to”, “be”, “as”, “is”, “it”, “the”). Combining these clues with the relative frequency of each letter, which in a natural language is far from uniform, a cryptanalyst can typically recover the key within a few minutes <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why it is so easy to break
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ease of the cryptanalysis lies not only in the algorithm itself, but in the fact that the attacker has access to far more information than just the algorithm and the ciphertext: they know the language of the message and its structure (where words begin and end). Hiding that structure, by removing the spaces from the ciphertext, makes a manual attack harder, but not impossible: other statistical features of the language, such as the frequency of consecutive letter pairs, remain available.</p>
</div>
</div>
<p><strong>Worked exercise: cryptanalysis via digraphs and trigraphs.</strong> A short word that repeats in the message, as a separate, complete word, always produces the same block of letters in the ciphertext, since the Caesar cipher applies a fixed shift. Consider the following ciphertext <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<div class="httpmsg">
<pre><code>Ciphertext:  YT GJ TW STY YT GJ YMFY NX YMJ VZJXYNTS</code></pre>
</div>
<p>The text has two blocks that repeat, each one twice: <strong>YT</strong> and <strong>GJ</strong>. In English, “to” is one of the most common two-letter words, and “the” one of the most common three-letter words. A natural first guess is that “YT” corresponds to “to”; trying that hypothesis against the rest of the ciphertext already reveals a partial, encouraging pattern. Adding the guess that a further three-letter block corresponds to “the” completes the picture. Assuming that YT corresponds to “TO” and the block YMJ to “THE”:</p>
<p><span class="math display">\[k = (\text{Y} - \text{T}) \bmod 26 = (24 - 19) \bmod 26 = 5\]</span></p>
<p>Note that it is essential for “to” and “the” to appear as separate words, never embedded inside a larger word, since only a repeated, isolated word guarantees an identical block of ciphertext.</p>
<p>With <span class="math inline">\(k = 5\)</span> known, the rest of the text decrypts immediately, word by word:</p>
<div class="httpmsg">
<pre><code>Plaintext:  TO BE OR NOT TO BE THAT IS THE QUESTION</code></pre>
</div>
<p>“To be, or not to be, that is the question” — the opening line of Hamlet’s soliloquy, from Shakespeare’s <em>Hamlet</em> (Act 3, Scene 1).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: break it yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Applying the same technique, break the following ciphertext (this time with no spaces between words):</p>
<div class="httpmsg">
<pre><code>JUURBFNUUCQJCNWMBFNUU</code></pre>
</div>
</div>
</div>
</section>
<section id="sec-01-monoalfabetica" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="sec-01-monoalfabetica"><span class="header-section-number">1.2.2</span> The monoalphabetic cipher</h3>
<p>The Caesar cipher is a very restricted special case of a more general class: the <strong>monoalphabetic cipher</strong>, in which the key is an arbitrary permutation of the 26 letters of the alphabet, not merely a fixed shift. The key space grows from 25 to <span class="math inline">\(26! \approx 4 \times 10^{26}\)</span>, making a brute-force attack computationally infeasible. For example:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
<th style="text-align: center;">J</th>
<th style="text-align: center;">K</th>
<th style="text-align: center;">L</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">O</th>
<th style="text-align: center;">P</th>
<th style="text-align: center;">Q</th>
<th style="text-align: center;">R</th>
<th style="text-align: center;">S</th>
<th style="text-align: center;">T</th>
<th style="text-align: center;">U</th>
<th style="text-align: center;">V</th>
<th style="text-align: center;">W</th>
<th style="text-align: center;">X</th>
<th style="text-align: center;">Y</th>
<th style="text-align: center;">Z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">J</td>
<td style="text-align: center;">G</td>
<td style="text-align: center;">I</td>
<td style="text-align: center;">U</td>
<td style="text-align: center;">Z</td>
<td style="text-align: center;">M</td>
<td style="text-align: center;">V</td>
<td style="text-align: center;">B</td>
<td style="text-align: center;">L</td>
<td style="text-align: center;">X</td>
<td style="text-align: center;">W</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">E</td>
<td style="text-align: center;">D</td>
<td style="text-align: center;">H</td>
<td style="text-align: center;">Y</td>
<td style="text-align: center;">T</td>
<td style="text-align: center;">K</td>
<td style="text-align: center;">Q</td>
<td style="text-align: center;">N</td>
<td style="text-align: center;">P</td>
<td style="text-align: center;">R</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">F</td>
<td style="text-align: center;">S</td>
<td style="text-align: center;">O</td>
</tr>
</tbody>
</table>
<p>Despite the astronomically larger key space, the monoalphabetic cipher remains vulnerable to cryptanalysis by frequency analysis: since each plaintext letter always corresponds to the same ciphertext letter, the statistical distribution of the plaintext letters carries over, intact, into the ciphertext, with only the symbols swapped. Comparing the frequency of the letters in the ciphertext with the known letter frequencies of the plaintext’s language is enough to reconstruct much of the correspondence, even without ever recovering the full permutation directly.</p>
<p>In English, the distribution of letters is far from uniform: E, T and A clearly dominate, followed by an intermediate group (O, I, N, S, H, R, D, L), and a set of rare letters (above all J, X, Q, Z, virtually absent as anything but the rare, distinctive appearance):</p>
<div id="fig-01-frequencia-letras" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-frequencia-letras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-frequencia-letras-en.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-frequencia-letras-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Letter frequency in English, as standardly published in the cryptographic literature <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>.
</figcaption>
</figure>
</div>
<p><strong>Worked exercise: a classic ciphertext.</strong> Consider the following ciphertext, 120 letters long, encrypted with a single, fixed monoalphabetic substitution <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<div class="httpmsg">
<pre><code>UZQSOVUOHXMOPVGPOZPEVSGZWSZOPFPESXUDBMETSXAIZ
VUEPHZHMDZSHZOWSFPAPPDTSVPQUZWYMXUZUHSX
EPYEPOPDZSZUFPOMBZWPFUPZHMDJUDTMOHMQ</code></pre>
</div>
<p>Counting the letters of this ciphertext gives the following frequency table (the most frequent letters only):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Ciphertext letter</th>
<th style="text-align: center;">Observed frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">P</td>
<td style="text-align: center;">13.33%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Z</td>
<td style="text-align: center;">11.67%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">S</td>
<td style="text-align: center;">8.33%</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">8.33%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">O</td>
<td style="text-align: center;">7.50%</td>
</tr>
<tr class="even">
<td style="text-align: center;">M</td>
<td style="text-align: center;">6.67%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">H</td>
<td style="text-align: center;">5.83%</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">5.00%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">E</td>
<td style="text-align: center;">5.00%</td>
</tr>
</tbody>
</table>
<p>Comparing this table with the reference chart (<a href="#fig-01-frequencia-letras" class="quarto-xref">Figure&nbsp;<span>1.2</span></a>): P, the most frequent ciphertext letter by a wide margin, is the natural candidate for E (12.7%), the most frequent letter of English; Z, the second most frequent, is the natural candidate for T (9.1%), the second most frequent letter of the language — a direct and safe correspondence, because the gap between these two values and the third-placed letter is wide enough to leave no doubt. From here, however, direct correspondence stops being reliable: both the ciphertext and the reference chart have several values that are close together or effectively tied from the 3rd position onward (8.33% vs.&nbsp;8.33%; 5.00% vs.&nbsp;5.00%; 4.17% vs.&nbsp;4.17%), and with only 120 letters these small differences carry little statistical weight. Matching position by position, purely mechanically, with no other clue:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">#</th>
<th style="text-align: center;">Ciphertext</th>
<th style="text-align: center;">English ref.</th>
<th style="text-align: center;">Direct guess</th>
<th style="text-align: center;">Real key</th>
<th style="text-align: center;">Hit?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">P (13.33%)</td>
<td style="text-align: center;">E (12.70%)</td>
<td style="text-align: center;">P→E</td>
<td style="text-align: center;">P→E</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">Z (11.67%)</td>
<td style="text-align: center;">T (9.06%)</td>
<td style="text-align: center;">Z→T</td>
<td style="text-align: center;">Z→T</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">U (8.33%)</td>
<td style="text-align: center;">A (8.17%)</td>
<td style="text-align: center;">U→A</td>
<td style="text-align: center;">U→I</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">S (8.33%)</td>
<td style="text-align: center;">O (7.51%)</td>
<td style="text-align: center;">S→O</td>
<td style="text-align: center;">S→A</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">O (7.50%)</td>
<td style="text-align: center;">I (6.97%)</td>
<td style="text-align: center;">O→I</td>
<td style="text-align: center;">O→S</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">M (6.67%)</td>
<td style="text-align: center;">N (6.75%)</td>
<td style="text-align: center;">M→N</td>
<td style="text-align: center;">M→O</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">H (5.83%)</td>
<td style="text-align: center;">S (6.33%)</td>
<td style="text-align: center;">H→S</td>
<td style="text-align: center;">H→C</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">E (5.00%)</td>
<td style="text-align: center;">H (6.09%)</td>
<td style="text-align: center;">E→H</td>
<td style="text-align: center;">E→R</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">D (5.00%)</td>
<td style="text-align: center;">R (5.99%)</td>
<td style="text-align: center;">D→R</td>
<td style="text-align: center;">D→N</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">V (4.17%)</td>
<td style="text-align: center;">D (4.25%)</td>
<td style="text-align: center;">V→D</td>
<td style="text-align: center;">V→D</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">11</td>
<td style="text-align: center;">X (4.17%)</td>
<td style="text-align: center;">L (4.03%)</td>
<td style="text-align: center;">X→L</td>
<td style="text-align: center;">X→L</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">12</td>
<td style="text-align: center;">W (3.33%)</td>
<td style="text-align: center;">C (2.78%)</td>
<td style="text-align: center;">W→C</td>
<td style="text-align: center;">W→H</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td style="text-align: center;">13</td>
<td style="text-align: center;">F (3.33%)</td>
<td style="text-align: center;">U (2.76%)</td>
<td style="text-align: center;">F→U</td>
<td style="text-align: center;">F→V</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td style="text-align: center;">14</td>
<td style="text-align: center;">Q (2.50%)</td>
<td style="text-align: center;">M (2.41%)</td>
<td style="text-align: center;">Q→M</td>
<td style="text-align: center;">Q→W</td>
<td style="text-align: center;">no</td>
</tr>
</tbody>
</table>
<p>Only 4 of these 14 correspondences (29%) coincide with the real key, and the mismatches start right after the dominant pair. This is not a weakness of this particular example: it is the realistic situation for any intercepted message of moderate length. Frequency analysis alone never fully decrypts a message on its own; it only narrows the field for the most and least common letters, leaving most of the alphabet unresolved.</p>
<p><strong>Digraphs and trigraphs, once more.</strong> To go further, the cryptanalyst falls back on the technique already used above with “to” and “the”: look for blocks of letters that repeat in the ciphertext, and test them against short, frequent words or word fragments of the language. Because this is a simple substitution, a repeated sequence of letters produces the same ciphertext block wherever it occurs — even when the repetition straddles a word boundary rather than reproducing a whole word. Counting the 3- to 5-letter blocks that repeat across the 120 letters of ciphertext, one stands out immediately: <strong>ZHMD</strong>, which occurs twice.</p>
<p>Since Z is already known to correspond to T, a natural hypothesis is that ZHMD begins a word starting with “T”. A second repeated block, <strong>DZS</strong> (also twice), shares the same D and Z, and decodes consistently as “…NTA…” once D is guessed as N — exactly the pattern found inside “co<strong>nta</strong>cts” and “represe<strong>nta</strong>tives”. Testing ZHMD as “TCON” — the fragment shared by “direc<strong>TCON</strong>tacts” and “vie<strong>TCON</strong>g” — fits both repeated occurrences perfectly and yields three new letters at once: H→C, M→O, D→N. Combined with S→A (confirmed by the “NTA” pattern) and the two already known (P→E, Z→T), six letters of the key are now fixed without any brute force. Applying them to the ciphertext already makes the message legible in patches:</p>
<div class="httpmsg">
<pre><code>...UEPHZHMDZSHZOWSFPAPPDTSVPQUZWYMXUZUHSX...
...___ECTCONTACT__A_E_EEN_A_E__T__O__T_CA_...</code></pre>
</div>
<p>“__ECT CONTACT__A_E _EEN _A_E __T_ _O__T_CA_” is already unmistakably “…irect contacts have been made with…ical…”. The remaining gaps close by vocabulary, exactly as before, revealing the full sentence:</p>
<blockquote class="blockquote">
<p>“It was disclosed yesterday that several informal but direct contacts have been made with political representatives of the Viet Cong in Moscow.”</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What if the ciphertext kept the spaces?
</div>
</div>
<div class="callout-body-container callout-body">
<p>If word boundaries were visible, the attack would change shape again. This particular sentence has no single-letter words, and none of its three short words repeats (<strong>IT</strong>, <strong>OF</strong>, <strong>IN</strong>; <strong>WAS</strong>, <strong>BUT</strong>, <strong>THE</strong>). But spaces still help decisively: once the dominant pair P→E and Z→T is known, a 3-letter word beginning with Z and ending in P is almost certainly “the” — by far the most common three-letter word in English — without needing to search the ciphertext for any hidden repetition. Here that word is ciphered as “ZWP”, so that single, targeted test gives W→H immediately, a letter the boundary-spanning “TCON” crib above never touched.</p>
</div>
</div>
</section>
<section id="sec-01-playfair" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="sec-01-playfair"><span class="header-section-number">1.2.3</span> The Playfair cipher</h3>
<p>The Playfair cipher reduces the problem above by encrypting <strong>pairs of letters</strong> (digraphs), rather than isolated letters, using a <span class="math inline">\(5 \times 5\)</span> grid built from a keyword. By encrypting pairs instead of individual letters, the frequency distribution of isolated letters no longer carries over directly into the ciphertext, making simple frequency analysis harder.</p>
<p><strong>Building the grid.</strong> A keyword is chosen, its letters (without repetitions) are written into the first positions of the grid, and the remaining positions are filled with the letters of the alphabet in order, skipping those already used. Since the grid has only 25 positions for 26 letters, “I” and “J” share the same cell. With the keyword “ESIGELEC” (a partner’s French Engineering School), after removing its repeated letters:</p>
<div id="fig-01-playfair-grelha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-playfair-grelha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-playfair-grelha-en.png" class="img-fluid figure-img" style="width:44.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-playfair-grelha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: Playfair grid built from the keyword “ESIGELEC”.
</figcaption>
</figure>
</div>
<p><strong>Encryption rules</strong>, applied to each pair of plaintext letters:</p>
<ul>
<li>If the two letters are in the <strong>same row</strong>, each is replaced by the letter immediately to its right (wrapping around to the start of the row, if necessary).</li>
<li>If the two letters are in the <strong>same column</strong>, each is replaced by the letter immediately below it (wrapping around to the top, if necessary).</li>
<li>Otherwise, each letter is replaced by the letter on its own row, but in the column of the other letter (the two letters and their replacements form a rectangle in the grid).</li>
</ul>
<p>If the two letters of a pair are identical, or if a single letter is left over at the end of a text with an odd number of letters, a filler letter is inserted (here, “X”).</p>
<p>Consider the phrase “ALL IS WELL”. Without spaces, and split into pairs (a repeated letter within a pair is separated with a filler “X”):</p>
<div class="httpmsg">
<pre><code>AL LI SW EL LX</code></pre>
</div>
<p>Applying the rules: “AL” shares no row or column, so the rectangle rule gives FS. “LI” is in the same row, giving EG. “SW” is in the same column, giving AS. “EL” is in the same row, giving SE. “LX” shares no row or column, giving IZ. The final ciphertext:</p>
<div class="httpmsg">
<pre><code>FSEGASSEIZ</code></pre>
</div>
<p>Even so, Playfair remains vulnerable: the frequency distribution of letter pairs (digraphs) in a natural language is likewise non-uniform, and this asymmetry survives encryption in a manner analogous to that of isolated letters. A cryptanalyst with enough ciphertext can reconstruct the grid through digraph frequency analysis.</p>
</section>
<section id="sec-01-vigenere" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="sec-01-vigenere"><span class="header-section-number">1.2.4</span> Polyalphabetic cipher: Vigenère</h3>
<p>The ciphers above share a structural weakness: each plaintext letter always corresponds to the same letter (or pair of letters) in the ciphertext, throughout the whole message. <strong>Polyalphabetic ciphers</strong> remove this fixed correspondence, using several different substitutions across the text, cycled according to a keyword that repeats itself.</p>
<p>In the Vigenère cipher, the keyword defines a sequence of shifts (each letter of the key corresponds to a different Caesar shift), applied cyclically to the successive letters of the plaintext. With <span class="math inline">\(m\)</span> the length of the keyword, and <span class="math inline">\(k_0, k_1, \dots, k_{m-1}\)</span> the shifts it defines:</p>
<p><span class="math display">\[C_i = (p_i + k_{i \bmod m}) \bmod 26 \qquad p_i = (C_i - k_{i \bmod m}) \bmod 26\]</span></p>
<p>Since the key is shorter than the message (<span class="math inline">\(m\)</span> is typically much smaller than the number of plaintext letters), the index <span class="math inline">\(i \bmod m\)</span> makes it repeat cyclically until it covers the whole text. The same plaintext letter can thus correspond to different ciphertext letters, depending on the position at which it occurs, which considerably flattens the frequency distribution observable in the ciphertext.</p>
<p><a href="#fig-01-achatamento-frequencia" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> shows this effect directly: for each cipher, the ciphertext letters are ranked from most to least frequent and normalised against the most common letter’s frequency. Plaintext produces a steeply sloped curve, with a small number of letters dominating. Playfair flattens it moderately, by substituting pairs of letters rather than single letters. Vigenère flattens it further still, precisely through the mechanism described above. A polyalphabetic cipher with a key as long as it is (pseudo)random approaches a nearly horizontal line, with no letter standing out at all — that is the line the One-Time Pad, further ahead, reaches perfectly.</p>
<div id="fig-01-achatamento-frequencia" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-achatamento-frequencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-01-achatamento-frequencia.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-achatamento-frequencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Flattening of the frequency distribution: as a cipher approaches the ideal polyalphabetic case, the ranked-frequency curve becomes flatter, eliminating the statistical information that frequency cryptanalysis would exploit.
</figcaption>
</figure>
</div>
<p>Using the keyword “deceptive” and the plaintext “we are discovered save yourself” <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>:</p>
<div class="httpmsg">
<pre><code>Key:         D E C E P T I V E D E C E P T I V E D E C E P T I V E
Plaintext:   W E A R E D I S C O V E R E D S A V E Y O U R S E L F
Ciphertext:  Z I C V T W Q N G R Z G V T W A V Z H C Q Y G L M G J
                    ^ ^ ^                 ^ ^ ^</code></pre>
</div>
<p>Notice the block <strong>VTW</strong>, which appears twice in the ciphertext, 9 positions apart. This is not a repeated word this time, it is a genuine coincidence of the plaintext itself: the sequence “red” appears once spanning the boundary between “wea<strong>re</strong>” and “<strong>d</strong>iscovered”, and again inside “disco<strong>vered</strong>” itself, exactly 9 letters later. Since the keyword “deceptive” also has 9 letters, both occurrences of “red” align with the key in exactly the same way, producing the same ciphertext block. This is the principle behind the Kasiski examination: whenever a stretch of plaintext repeats at a distance that is a multiple of the key length, even by coincidence, the corresponding ciphertext repeats too, and that visible repetition is a direct clue to the length of the key, here, 9.</p>
<p>The Vigenère cipher resisted systematic cryptanalysis for centuries, but it is not unbreakable: if the key is short and repeated many times over a sufficiently long text, techniques such as the Kasiski examination (identifying repetitions in the ciphertext, which reveal multiples of the key length) allow the key length to be recovered, and from there the text can be treated as several independent Caesar ciphers, one for each position within the key’s cycle.</p>
<p>Knowing already, from the Kasiski examination alone, that the key has 9 letters (without yet knowing which ones), the cryptanalyst regroups the ciphertext: all the letters in positions 1, 10, 19, … form a first group; positions 2, 11, 20, … form a second group; and so on up to the ninth group. Each group, taken in isolation, is an ordinary Caesar cipher, with a single fixed <span class="math inline">\(k\)</span>, exactly the kind of problem already solved in the previous section:</p>
<div class="httpmsg">
<pre><code>Group 1 (pos. 1, 10, 19):  Z R H
Group 2 (pos. 2, 11, 20):  I Z C
Group 3 (pos. 3, 12, 21):  C G Q
Group 4 (pos. 4, 13, 22):  V V Y
Group 5 (pos. 5, 14, 23):  T T G
Group 6 (pos. 6, 15, 24):  W W L
Group 7 (pos. 7, 16, 25):  Q A M
Group 8 (pos. 8, 17, 26):  N V G
Group 9 (pos. 9, 18, 27):  G Z J</code></pre>
</div>
<p>Note that this does not contradict what was said above about Vigenère flattening the frequency distribution: that distortion affects the ciphertext <em>as a whole</em>, where letters encrypted with different shifts are mixed together. Within each isolated group, however, the same shift was always used, so the distribution reverts to that of an ordinary Caesar cipher, with no flattening at all. The Kasiski examination and frequency analysis therefore solve two different, complementary problems: one gives the number of groups to form (the key length); the other, applied afterwards to each group separately, gives the shift of each one.</p>
<p>To each group is applied, in isolation, the same single-letter frequency analysis used against the Caesar cipher: which is the most frequent letter of this group, and which letter of the language should it correspond to? In this example, with only 3 letters per group, there is not enough data for that analysis to be reliable; in a real, considerably longer text, each group would have dozens or hundreds of letters, and the method would work just as well as it did against the Caesar cipher.</p>
</section>
<section id="sec-01-vernam" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="sec-01-vernam"><span class="header-section-number">1.2.5</span> The Vernam cipher</h3>
<p>Before reaching the definitive solution, it is worth taking one intermediate step. The <strong>Vernam cipher</strong>, created by Gilbert Vernam at AT&amp;T laboratories in 1918 for telegraphy <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>, generalises Vigenère in two ways: it replaces modular addition with a bitwise <strong>XOR</strong> operation, and it uses a key much longer than the short keyword typical of Vigenère, to the point of being, in practice, as long as the punched paper tape that implemented it.</p>
<p><span class="math display">\[C_i = P_i \oplus K_{i \bmod m} \qquad P_i = C_i \oplus K_{i \bmod m}\]</span></p>
<div id="fig-01-vernam-gerador" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-vernam-gerador-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-vernam-gerador-en.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-vernam-gerador-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: The Vernam cipher: a keystream generator produces the sequence <span class="math inline">\(k_i\)</span>, combined by XOR with the plaintext during encryption, and with the ciphertext during decryption — the same operation in both directions.
</figcaption>
</figure>
</div>
<p>A much longer key considerably hinders the Kasiski examination, since repetitions in the ciphertext become much rarer. But the underlying problem does not disappear: sooner or later, even a very long key tape runs out and has to start again, reintroducing a cycle, albeit a much larger one than a Vigenère keyword’s. The Vernam cipher is therefore a substantial improvement over Vigenère, but not a definitive solution: it remains vulnerable, in principle, to the same kind of cryptanalysis, only requiring much longer intercepted messages to become practicable.</p>
<p>Note a structural limitation of the Vernam cipher as originally conceived: it uses only a key, with no other value to distinguish one message from the next. It is precisely this absence that forces the key tape to repeat once it runs out. Modern stream ciphers, taken up again in Chapter 4, solve this problem by introducing a second value, the <em>nonce</em>, unique per message but not secret, which allows the same key to be reused safely from message to message, without ever repeating the keystream.</p>
</section>
<section id="sec-01-otp" class="level3" data-number="1.2.6">
<h3 data-number="1.2.6" class="anchored" data-anchor-id="sec-01-otp"><span class="header-section-number">1.2.6</span> The One-Time Pad</h3>
<p>The <strong>One-Time Pad</strong> definitively resolves the weakness that the Vernam cipher only mitigated: it uses a genuinely random key, the same length as the message, never reused for another message, and therefore never subject to any cycle at all. Each plaintext letter is combined with the corresponding key letter, just as in Vigenère, but without any cycle, since the key is exactly as long as the text itself.</p>
<p>Claude Shannon proved, in 1949, that the One-Time Pad, when used correctly, is <strong>mathematically unbreakable</strong>: the ciphertext reveals no information whatsoever about the plaintext, even with unlimited computational power <span class="citation" data-cites="Shannon1949">(<a href="cap01.html#ref-Shannon1949" role="doc-biblioref">Shannon 1949</a>)</span>. This property is called <strong>perfect secrecy</strong>.</p>
<p><strong>A concrete example of perfect secrecy.</strong> For any ciphertext <span class="math inline">\(C\)</span> and any plaintext <span class="math inline">\(P\)</span> of the same length, there is always exactly one key <span class="math inline">\(K = (C - P) \bmod 26\)</span> linking them. Since every key is, a priori, equally likely, the ciphertext does not favour any one reading over another: for a given ciphertext, there is always some key that decrypts it into any plaintext one likes, of the same length.</p>
<p>This can be demonstrated concretely. Fixing a single 22-letter ciphertext, three different keys decrypt it into three plausible, mutually exclusive solutions:</p>
<div class="httpmsg">
<pre><code>Ciphertext (fixed):    G L S P A J H V I H O Q Z P L U F S V A K O

Key 1: U D A X I H H E X D V X R C S N B A C G H Q
Decrypts to: MISS SCARLETT IN THE STUDY

Key 2: U U A A W J F H G X G D G I H J X R E A T Q
Decrypts to: MRS PEACOCK IN THE LIBRARY

Key 3: E X H B N F W J O P V Q I M D H M L R X G B
Decrypts to: COLONEL MUSTARD IN THE DEN</code></pre>
</div>
<p>All three decryptions are correct: each results from applying <span class="math inline">\(p = (C - K) \bmod 26\)</span>, letter by letter, with the respective key. An attacker who intercepts only <code>GLSPAJHVIHOQZPLUFSVAKO</code>, without knowing the key, has no way whatsoever of knowing whether the culprit is in the study, the library, or the den. These three readings, and infinitely many others of the same length, are all equally compatible with the ciphertext.</p>
<p>Despite this absolute theoretical guarantee, the One-Time Pad is impractical in most real-world scenarios, for three requirements that are hard to satisfy simultaneously:</p>
<ul>
<li>the key must be as long as the message;</li>
<li>the key must be genuinely random, not generated by a deterministic algorithm;</li>
<li>the key can never be reused, not even partially.</li>
</ul>
<p>Distributing and storing keys of this size, securely, is just as hard as securely distributing the message itself. There is also a less obvious cost: generating, in a genuinely random way, and then securely managing a large volume of keys of this size also carries a non-trivial computational cost, which can make the process too slow for most practical applications. These combined requirements limit the use of the One-Time Pad to very specific scenarios, such as certain diplomatic or military communications of exceptional importance.</p>
</section>
<section id="sec-01-enigma" class="level3" data-number="1.2.7">
<h3 data-number="1.2.7" class="anchored" data-anchor-id="sec-01-enigma"><span class="header-section-number">1.2.7</span> The Enigma machine</h3>
<p>Enigma, used by Germany before and during the Second World War, is also a polyalphabetic cipher: as in Vigenère, the same plaintext letter corresponds to different ciphertext letters depending on the position at which it occurs. The difference lies in how that variation is generated. In Vigenère, a short keyword, repeated cyclically, determines the shift applied at each position; in Enigma, that role falls to a set of electromechanical <strong>rotors</strong> that advance one position with every keystroke, altering the electrical circuit that connects each input letter to its corresponding output letter. The effect is the same as in Vigenère (a different substitution at every position), but the “key length” before the cycle repeats grows from a handful of memorable letters to tens of thousands of positions — impractical to exploit through classical frequency analysis, though, unlike the One-Time Pad, far from mathematically unbreakable.</p>
<p>It is important not to confuse the rotors with the key itself. Enigma’s key, changed daily, was the set of settings that sender and receiver had to share in advance: which rotors to use and in what order, their initial position, the internal ring setting of each rotor, and the plugboard connections (which swapped pairs of letters before and after the rotors). The rotors do not generate this key: it is the key that determines how the rotors (and the plugboard) behave. What the rotors generate, mechanically, letter by letter, is the sequence of substitutions that this initial key sets in motion — the mechanical counterpart of the sequence of shifts that, in Vigenère, the keyword generates by repeating itself.</p>
<p>Enigma was never broken by conventional frequency analysis: the period was far too long for any letter count to be useful. It was broken instead by a combination of a structural design flaw (the internal wiring guaranteed that no letter could ever be enciphered as itself, which eliminated hypotheses and made testing easier) and the very same probable-word (“<em>crib</em>”) technique already used in this chapter: certain German messages almost always contained the same words in the same positions, such as the daily weather report (“<em>Wetterbericht</em>”), which allowed strong hypotheses about fragments of plaintext to be formed without any statistical analysis at all. Testing those hypotheses against the enormous space of possible settings, however, demanded an amount of computation impractical by hand; the Bombe, developed by Alan Turing and Gordon Welchman at Bletchley Park building on earlier mathematical work by Polish cryptanalysts <span class="citation" data-cites="Rejewski1981">(<a href="cap01.html#ref-Rejewski1981" role="doc-biblioref">Rejewski 1981</a>)</span>, mechanised exactly that test at scale, anticipating many of the principles of the electronic computers that would follow <span class="citation" data-cites="Kahn1967">(<a href="cap01.html#ref-Kahn1967" role="doc-biblioref">Kahn 1967</a>)</span>.</p>
</section>
</section>
<section id="sec-01-transposicao" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-01-transposicao"><span class="header-section-number">1.3</span> Transposition Ciphers</h2>
<p>Unlike substitution ciphers, <strong>transposition ciphers</strong> do not change the identity of the plaintext symbols, only their order. The ciphertext contains exactly the same letters as the plaintext, merely rearranged according to a rule determined by the key.</p>
<section id="sec-01-rail-fence" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="sec-01-rail-fence"><span class="header-section-number">1.3.1</span> The rail fence technique</h3>
<p>The simplest form of transposition is the <strong>rail fence</strong> technique: the plaintext is written alternately across two lines, forming a zigzag, and the ciphertext is obtained by reading first the top line, then the bottom line, without interruption.</p>
<p>For the plaintext “WE ARE DISCOVERED FLEE AT ONCE” (without spaces, 25 letters):</p>
<div id="fig-01-rail-fence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-rail-fence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-rail-fence-en.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-rail-fence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.6: The rail fence technique: the plaintext is written in a zigzag across two lines; the ciphertext is read line by line.
</figcaption>
</figure>
</div>
<p>Reading Line 1 followed by Line 2 gives the ciphertext <code>WAEICVRDLETNEERDSOEEFEAOC</code>. Every letter of the ciphertext belongs to the plaintext, merely reordered, so statistical cryptanalysis based on isolated-letter frequency remains perfectly viable, as will be discussed further in this section.</p>
</section>
<section id="sec-01-transposicao-colunar" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="sec-01-transposicao-colunar"><span class="header-section-number">1.3.2</span> Columnar transposition</h3>
<p>A more elaborate technique is <strong>columnar transposition</strong>: the plaintext is written into a grid with a number of columns equal to the length of the keyword, and the ciphertext is obtained by reading the columns in the alphabetical order of the keyword’s letters, rather than the original order in which they were written.</p>
<p>Consider the key <code>4312567</code> and the plaintext “attack postponed until two am” <span class="citation" data-cites="Stallings2020">(<a href="cap01.html#ref-Stallings2020" role="doc-biblioref">Stallings 2020</a>)</span>, padded with “xyz” to complete the final row (28 letters, arranged in four rows of seven columns):</p>
<div id="fig-01-transposicao-grelha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-01-transposicao-grelha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/images/fig-transposicao-grelha-en.png" class="img-fluid figure-img" style="width:68.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-01-transposicao-grelha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.7: Columnar transposition grid with key 4312567. The digits above each column give the order in which the columns are read out.
</figcaption>
</figure>
</div>
<p>The ciphertext is obtained by reading the columns in the numerical order of their key digit (not the order in which they appear in the grid): first the column under key digit 1, then under digit 2, and so on up to the column under digit 7:</p>
<div class="httpmsg">
<pre><code>TTNAAPTMTSUOAODWCOIXKNLYPETZ</code></pre>
</div>
<p>Note that every letter of the plaintext is still present in the ciphertext, in the same quantity; only the order has changed.</p>
<p>A single columnar transposition is vulnerable to cryptanalysis, since the frequency distribution of isolated letters remains entirely unchanged, only their relative position changes. There is an important difference here compared with substitution: in a substitution, frequency is used to guess which plaintext letter corresponds to each ciphertext letter, a mapping problem; in a transposition, there is no mapping to guess at all, since an “E” in the ciphertext really is an “E” from the original text, merely shifted in position. The most frequent letter of the ciphertext is, therefore, directly the most frequent letter of the language, with no intermediate hypothesis needed — which even makes it possible to <strong>distinguish</strong> a transposition from a substitution purely from frequency: if the most frequent letter of the ciphertext coincides with the one expected for the language (E, in English), that is a sign of transposition, not substitution. What isolated-letter frequency does not reveal, on its own, is the reading order of the columns: for that, other clues are needed, such as frequent digraphs and trigraphs split in half by the grid, or trying various column widths. Repeating the transposition several times, with different keys (<strong>double</strong> or multiple transposition), considerably hinders manual reconstruction, although it remains vulnerable to modern computational attacks.</p>
<p>Historically, the combination of substitution and transposition, each weak in isolation but strong when combined, is the principle that gives rise to the modern concepts of <strong>confusion</strong> and <strong>diffusion</strong>, introduced by Shannon and central to the design of the modern block ciphers studied in the next chapter.</p>
</section>
</section>
<section id="sec-01-sintese" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-01-sintese"><span class="header-section-number">1.4</span> Chapter Summary</h2>
<p>This chapter established the vocabulary and fundamental principles that run through the whole discipline of cryptography:</p>
<ol type="1">
<li>A symmetric cryptographic system is defined by its five components, plaintext, encryption algorithm, secret key, ciphertext and decryption algorithm, related by <span class="math inline">\(Y = E(K, X)\)</span> and <span class="math inline">\(X = D(K, Y)\)</span></li>
<li><strong>Kerckhoffs’s principle</strong> establishes that the security of a cipher must depend solely on the secrecy of the key, never on the secrecy of the algorithm</li>
<li>An attacker has two general strategies available: <strong>brute force</strong> (exhaustively testing the key space) and <strong>cryptanalysis</strong> (exploiting additional information to deduce the key without testing it exhaustively)</li>
<li><strong>Substitution ciphers</strong> (Caesar, monoalphabetic, Playfair, Vigenère) replace plaintext symbols with other symbols, with decreasing, but never entirely eliminated, vulnerability to frequency-analysis attacks</li>
<li>The <strong>Vernam cipher</strong> generalises Vigenère with XOR and a much longer key, mitigating but not eliminating the problem of a repeating key; the <strong>One-Time Pad</strong> eliminates it completely, being the only classical cipher that is mathematically unbreakable, at the cost of key-management requirements that are impractical in most real-world scenarios</li>
<li><strong>Enigma</strong> mechanised the polyalphabetic principle on an industrial scale, replacing Vigenère’s short keyword with electromechanical rotors; it fell not to frequency analysis, but to a structural design flaw combined with probable words (“<em>cribs</em>”) tested at scale by the Bombe</li>
<li><strong>Transposition ciphers</strong> reorder the symbols of the plaintext without changing their identity, and form the historical basis of the modern concepts of confusion and diffusion</li>
</ol>
</section>
<section id="sec-01-reflexao" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-01-reflexao"><span class="header-section-number">1.5</span> Discussion Question</h2>
<p>Why is it that the One-Time Pad, despite being mathematically unbreakable, is not the universal solution to every problem of secure communication? What other problem, just as hard as that of the message itself, does its use end up introducing?</p>
</section>
<section id="sec-01-referencias" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-01-referencias">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-AlFardan2013" class="csl-entry" role="listitem">
AlFardan, Nadhem J., Daniel J. Bernstein, Kenneth G. Paterson, Bertram
Poettering, and Jacob C. N. Schuldt. 2013. <span>“On the Security of
<span>RC4</span> in <span>TLS</span>.”</span> In <em>22nd USENIX
Security Symposium</em>.
</div>
<div id="ref-Aumasson2017" class="csl-entry" role="listitem">
Aumasson, Jean-Philippe. 2017. <em>Serious Cryptography: A Practical
Introduction to Modern Encryption</em>. No Starch Press.
</div>
<div id="ref-NIST80057" class="csl-entry" role="listitem">
Barker, Elaine. 2020. <span>“Recommendation for Key Management, Part 1:
General.”</span> SP 800-57 Part 1 Rev. 5. NIST.
</div>
<div id="ref-BellareCanettiKrawczyk1996" class="csl-entry" role="listitem">
Bellare, Mihir, Ran Canetti, and Hugo Krawczyk. 1996. <span>“Keying Hash
Functions for Message Authentication.”</span> In <em>Advances in
Cryptology (CRYPTO ’96)</em>.
</div>
<div id="ref-Bernstein2005Poly1305" class="csl-entry" role="listitem">
Bernstein, Daniel J. 2005. <span>“The <span>Poly1305-AES</span>
Message-Authentication Code.”</span> In <em>Fast Software Encryption
(FSE 2005)</em>. Vol. 3557. Lecture Notes in Computer Science. Springer.
</div>
<div id="ref-Bernstein2006Curve25519" class="csl-entry" role="listitem">
———. 2006. <span>“Curve25519: New <span>Diffie-Hellman</span> Speed
Records.”</span> In <em>Public Key Cryptography (PKC 2006)</em>. Vol.
3958. Lecture Notes in Computer Science. Springer.
</div>
<div id="ref-Bock2016" class="csl-entry" role="listitem">
Böck, Hanno, Aaron Zauner, Sean Devlin, Juraj Somorovsky, and Philipp
Jovanovic. 2016. <span>“Nonce-Disrespecting Adversaries: Practical
Forgery Attacks on <span>GCM</span> in <span>TLS</span>.”</span> In
<em>USENIX Workshop on Offensive Technologies (WOOT)</em>.
</div>
<div id="ref-RFC4880" class="csl-entry" role="listitem">
Callas, Jon, Lutz Donnerhacke, Hal Finney, David Shaw, and Rodney
Thayer. 2007. <span>“<span>OpenPGP</span> Message Format.”</span> RFC
4880. IETF.
</div>
<div id="ref-RFC5280" class="csl-entry" role="listitem">
Cooper, David, Stefan Santesson, Stephen Farrell, Sharon Boeyen, Russell
Housley, and Tim Polk. 2008. <span>“Internet <span>X.509</span> Public
Key Infrastructure Certificate and Certificate Revocation List
(<span>CRL</span>) Profile.”</span> RFC 5280. IETF.
</div>
<div id="ref-Du2022" class="csl-entry" role="listitem">
Du, Wenliang. 2022. <em>Computer Security: A Hands-on Approach</em>. 3rd
ed. CreateSpace / Self-published.
</div>
<div id="ref-NIST80038A" class="csl-entry" role="listitem">
Dworkin, Morris. 2001. <span>“Recommendation for Block Cipher Modes of
Operation: Methods and Techniques.”</span> SP 800-38A. NIST.
</div>
<div id="ref-NIST80038D" class="csl-entry" role="listitem">
———. 2007. <span>“Recommendation for Block Cipher Modes of Operation:
<span>Galois/Counter</span> Mode (GCM) and <span>GMAC</span>.”</span> SP
800-38D. NIST.
</div>
<div id="ref-FMS2001" class="csl-entry" role="listitem">
Fluhrer, Scott, Itsik Mantin, and Adi Shamir. 2001. <span>“Weaknesses in
the Key Scheduling Algorithm of <span>RC4</span>.”</span> In
<em>Selected Areas in Cryptography (SAC 2001)</em>.
</div>
<div id="ref-Grover1996" class="csl-entry" role="listitem">
Grover, Lov K. 1996. <span>“A Fast Quantum Mechanical Algorithm for
Database Search.”</span> In <em>28th Annual ACM Symposium on Theory of
Computing (STOC)</em>.
</div>
<div id="ref-Kahn1967" class="csl-entry" role="listitem">
Kahn, David. 1967. <em>The Codebreakers: The Story of Secret
Writing</em>. New York: Macmillan.
</div>
<div id="ref-Kerckhoffs1883" class="csl-entry" role="listitem">
Kerckhoffs, Auguste. 1883. <span>“La Cryptographie Militaire.”</span>
<em>Journal Des Sciences Militaires</em> 9: 5–38.
</div>
<div id="ref-Koblitz1987" class="csl-entry" role="listitem">
Koblitz, Neal. 1987. <span>“Elliptic Curve Cryptosystems.”</span>
<em>Mathematics of Computation</em> 48 (177): 203–9.
</div>
<div id="ref-RFC2104" class="csl-entry" role="listitem">
Krawczyk, Hugo, Mihir Bellare, and Ran Canetti. 1997.
<span>“<span>HMAC</span>: Keyed-Hashing for Message
Authentication.”</span> RFC 2104. IETF.
</div>
<div id="ref-RFC7748" class="csl-entry" role="listitem">
Langley, Adam, Mike Hamburg, and Sean Turner. 2016. <span>“Elliptic
Curves for Security.”</span> RFC 7748. IETF.
</div>
<div id="ref-Martin2017" class="csl-entry" role="listitem">
Martin, Keith. 2017. <em>Everyday Cryptography</em>. 2nd ed. Oxford
University Press.
</div>
<div id="ref-Miller1985" class="csl-entry" role="listitem">
Miller, Victor S. 1985. <span>“Use of Elliptic Curves in
Cryptography.”</span> In <em>Advances in Cryptology (CRYPTO ’85)</em>.
</div>
<div id="ref-FIPS197" class="csl-entry" role="listitem">
National Institute of Standards and Technology. 2001. <span>“Advanced
Encryption Standard (AES).”</span> FIPS PUB 197. NIST.
</div>
<div id="ref-FIPS1804" class="csl-entry" role="listitem">
———. 2015. <span>“Secure Hash Standard (SHS).”</span> FIPS PUB 180-4.
NIST.
</div>
<div id="ref-FIPS204" class="csl-entry" role="listitem">
———. 2024a. <span>“Module-Lattice-Based Digital Signature
Standard.”</span> FIPS PUB 204. NIST.
</div>
<div id="ref-FIPS203" class="csl-entry" role="listitem">
———. 2024b. <span>“Module-Lattice-Based Key-Encapsulation Mechanism
Standard.”</span> FIPS PUB 203. NIST.
</div>
<div id="ref-RFC8439" class="csl-entry" role="listitem">
Nir, Yoav, and Adam Langley. 2018. <span>“<span>ChaCha20</span> and
<span>Poly1305</span> for <span>IETF</span> Protocols.”</span> RFC 8439.
IETF.
</div>
<div id="ref-RFC7465" class="csl-entry" role="listitem">
Popov, Andrei. 2015. <span>“Prohibiting <span>RC4</span> Cipher
Suites.”</span> RFC 7465. IETF.
</div>
<div id="ref-PreneelOorschot1995" class="csl-entry" role="listitem">
Preneel, Bart, and Paul C. van Oorschot. 1995.
<span>“<span>MDx-MAC</span> and Building Fast <span>MAC</span>s from
Hash Functions.”</span> In <em>Advances in Cryptology (CRYPTO ’95)</em>.
</div>
<div id="ref-Rejewski1981" class="csl-entry" role="listitem">
Rejewski, Marian. 1981. <span>“How <span>P</span>olish Mathematicians
Deciphered the <span>E</span>nigma.”</span> <em>Annals of the History of
Computing</em> 3 (3): 213–34.
</div>
<div id="ref-RFC8446" class="csl-entry" role="listitem">
Rescorla, Eric. 2018. <span>“The Transport Layer Security
(<span>TLS</span>) Protocol Version 1.3.”</span> RFC 8446. IETF.
</div>
<div id="ref-Shannon1949" class="csl-entry" role="listitem">
Shannon, Claude E. 1949. <span>“Communication Theory of Secrecy
Systems.”</span> <em>Bell System Technical Journal</em> 28 (4): 656–715.
</div>
<div id="ref-Shor1997" class="csl-entry" role="listitem">
Shor, Peter W. 1997. <span>“Polynomial-Time Algorithms for Prime
Factorization and Discrete Logarithms on a Quantum Computer.”</span>
<em>SIAM Journal on Computing</em> 26 (5): 1484–1509.
</div>
<div id="ref-Stallings2020" class="csl-entry" role="listitem">
Stallings, William. 2020. <em>Cryptography and Network Security:
Principles and Practice</em>. 8th ed. Pearson.
</div>
<div id="ref-Stevens2017" class="csl-entry" role="listitem">
Stevens, Marc, Elie Bursztein, Pierre Karpman, Ange Albertini, and Yarik
Markov. 2017. <span>“The First Collision for Full
<span>SHA-1</span>.”</span> In <em>Advances in Cryptology (CRYPTO
2017)</em>.
</div>
<div id="ref-Wang2005" class="csl-entry" role="listitem">
Wang, Xiaoyun, and Hongbo Yu. 2005. <span>“How to Break <span>MD5</span>
and Other Hash Functions.”</span> In <em>Advances in Cryptology
(EUROCRYPT 2005)</em>.
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/cap02.html" class="pagination-link" aria-label="Block Ciphers — Fundamentals, Feistel, DES and 3DES">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Block Ciphers — Fundamentals, Feistel, DES and 3DES</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Classical Cryptography — Substitution, Polyalphabetic and Transposition Ciphers"</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "João Pavão"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-09-14</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> en-GB</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction {#sec-01-intro .unnumbered}</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>Cryptography is the discipline that studies techniques for protecting information by transforming it into a form unreadable to anyone who does not possess the key needed to reverse that transformation. This chapter introduces the fundamental concepts that run through the entire discipline, the symmetric cipher model, Kerckhoffs's principle, the distinction between brute force and cryptanalysis, and then works through the classical ciphers: substitution and transposition systems developed over centuries, well before the appearance of the computer.</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>These ciphers are, from the point of view of practical security, completely obsolete today, trivial to break with modern computational resources. Their value in this module is pedagogical: they introduce, in a simple and manual way, the concepts of key, key space, brute-force attack and cryptanalysis that apply, with exactly the same logic, to the modern systems studied in the following chapters.</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fundamentals of Cryptographic Systems {#sec-01-fundamentos}</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="fu">### Classifying cryptographic systems {#sec-01-classificacao}</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>Cryptographic systems are classified according to three independent criteria:</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>| Criterion | Categories |</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>|:--|:--|</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>| Number of keys | **Symmetric** (a single key, shared between sender and receiver) or **asymmetric** (two distinct keys, one public and one private) |</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>| Type of operation | **Substitution** (each symbol is replaced by another) or **transposition** (the symbols themselves stay the same, but their order is changed) |</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>| Text processing | **Block cipher** (the text is processed in fixed-size blocks) or **stream cipher** (the text is processed continuously, symbol by symbol) |</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>This chapter deals exclusively with **symmetric** systems, of the **substitution** or **transposition** kind. The following chapters introduce modern block and stream ciphers.</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="fu">### The symmetric cipher model {#sec-01-modelo}</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>A symmetric cryptographic system is defined by five components <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Plaintext** ($X$): the original message, still intelligible.</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Encryption algorithm** ($E$): the procedure that transforms plaintext into ciphertext, through successive substitutions and transformations.</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Secret key** ($K$): a value independent of the plaintext and of the algorithm, shared between sender and receiver over a secure channel. Different keys produce different results for the same plaintext and the same algorithm.</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Ciphertext** ($Y$): the result of encryption, apparently random and, at first sight, unintelligible.</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Decryption algorithm** ($D$): essentially the encryption algorithm run in reverse, which uses the same key $K$ to recover the plaintext from the ciphertext.</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>Formally:</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>$$Y = E(K, X)$$</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>$$X = D(K, Y)$$</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a><span class="al">![The symmetric cipher model: sender and receiver have previously shared the same secret key, over a secure channel. The encryption algorithm uses that key to transform plaintext into ciphertext; the decryption algorithm, using the same key, reverses the transformation.](../assets/images/fig-modelo-cifra-simetrica-en.png)</span>{#fig-01-modelo-simetrico}</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>Sender and receiver must have obtained copies of the same secret key by some secure means, and kept it protected (@fig-01-modelo-simetrico). If someone discovers the key and knows the algorithm, all communication encrypted with that key becomes readable.</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kerckhoffs's principle {#sec-01-kerckhoffs}</span></span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>A fundamental assumption of all modern cryptography, already present in these classical ciphers, is **Kerckhoffs's principle**, formulated in 1883 <span class="co">[</span><span class="ot">@Kerckhoffs1883</span><span class="co">]</span>: the security of a cipher must depend solely on the secrecy of the key, never on the secrecy of the algorithm. It is always assumed that an attacker knows the encryption and decryption algorithm perfectly, only the key is unknown.</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a>This convention has an important practical consequence: an algorithm whose security depends on remaining secret (*security through obscurity*) is not considered secure in serious cryptography, precisely because that condition is impossible to guarantee in the long run. The algorithms studied in this module are all public and widely scrutinised: their security rests entirely on the size and the secrecy of the key.</span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a><span class="fu">### Brute force and cryptanalysis {#sec-01-ataques}</span></span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a>An attacker who wants to recover the plaintext without knowing the key has two general strategies available:</span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Brute force**: exhaustively test every possible key, until one is found that produces intelligible plaintext. On average, roughly half of the total key space must be tested to obtain a result.</span>
<span id="cb13-58"><a href="#cb13-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Cryptanalysis**: exploit additional knowledge about parts of the system, such as already-known plaintext/ciphertext pairs, or statistical properties of the algorithm, to deduce the key without testing it exhaustively.</span>
<span id="cb13-59"><a href="#cb13-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-60"><a href="#cb13-60" aria-hidden="true" tabindex="-1"></a>Classical cryptanalysis of the ciphers studied in this chapter relies chiefly on **frequency analysis**: the statistical distribution of letters in a natural language is not uniform, and that asymmetry survives, in varying degrees, the encryption process.</span>
<span id="cb13-61"><a href="#cb13-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-62"><a href="#cb13-62" aria-hidden="true" tabindex="-1"></a>Depending on the information available to the cryptanalyst, several types of attack are distinguished <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-63"><a href="#cb13-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-64"><a href="#cb13-64" aria-hidden="true" tabindex="-1"></a>| Type of attack | What the cryptanalyst knows |</span>
<span id="cb13-65"><a href="#cb13-65" aria-hidden="true" tabindex="-1"></a>|:--|:--|</span>
<span id="cb13-66"><a href="#cb13-66" aria-hidden="true" tabindex="-1"></a>| Ciphertext only | The algorithm and the ciphertext |</span>
<span id="cb13-67"><a href="#cb13-67" aria-hidden="true" tabindex="-1"></a>| Known plaintext | The algorithm, the ciphertext, and one or more plaintext/ciphertext pairs formed with the same key |</span>
<span id="cb13-68"><a href="#cb13-68" aria-hidden="true" tabindex="-1"></a>| Chosen plaintext | The algorithm, the ciphertext, and a plaintext chosen by the attacker, with the corresponding ciphertext |</span>
<span id="cb13-69"><a href="#cb13-69" aria-hidden="true" tabindex="-1"></a>| Chosen ciphertext | The algorithm, the ciphertext, and a ciphertext chosen by the attacker, with the corresponding decrypted plaintext |</span>
<span id="cb13-70"><a href="#cb13-70" aria-hidden="true" tabindex="-1"></a>| Chosen text | The combined knowledge of the two previous attacks |</span>
<span id="cb13-71"><a href="#cb13-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-72"><a href="#cb13-72" aria-hidden="true" tabindex="-1"></a><span class="fu">## Substitution Ciphers {#sec-01-substituicao}</span></span>
<span id="cb13-73"><a href="#cb13-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-74"><a href="#cb13-74" aria-hidden="true" tabindex="-1"></a>In a substitution cipher, each symbol of the plaintext is **replaced** by another symbol, according to a fixed rule determined by the key. The order of the symbols stays unchanged; what changes is their identity.</span>
<span id="cb13-75"><a href="#cb13-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-76"><a href="#cb13-76" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Caesar cipher {#sec-01-cesar}</span></span>
<span id="cb13-77"><a href="#cb13-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-78"><a href="#cb13-78" aria-hidden="true" tabindex="-1"></a>The Caesar cipher, attributed to Julius Caesar, is the simplest substitution cipher: each letter is replaced by the letter found $k$ positions further down the alphabet, with $k$ the key. For example, with $k = 3$, encrypting the instruction "meet me under the bridge" <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-79"><a href="#cb13-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-80"><a href="#cb13-80" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-81"><a href="#cb13-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-82"><a href="#cb13-82" aria-hidden="true" tabindex="-1"></a><span class="in">Plain:   M E E T   M E   U N D E R   T H E   B R I D G E</span></span>
<span id="cb13-83"><a href="#cb13-83" aria-hidden="true" tabindex="-1"></a><span class="in">Cipher:  P H H W   P H   X Q G H U   W K H   E U L G J H</span></span>
<span id="cb13-84"><a href="#cb13-84" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-85"><a href="#cb13-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-86"><a href="#cb13-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-87"><a href="#cb13-87" aria-hidden="true" tabindex="-1"></a>Numbering the letters of the alphabet from 0 (A) to 25 (Z), the Caesar cipher is formally defined by:</span>
<span id="cb13-88"><a href="#cb13-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-89"><a href="#cb13-89" aria-hidden="true" tabindex="-1"></a>$$C = E(k, p) = (p + k) \bmod 26$$</span>
<span id="cb13-90"><a href="#cb13-90" aria-hidden="true" tabindex="-1"></a>$$p = D(k, C) = (C - k) \bmod 26$$</span>
<span id="cb13-91"><a href="#cb13-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-92"><a href="#cb13-92" aria-hidden="true" tabindex="-1"></a>| A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z |</span>
<span id="cb13-93"><a href="#cb13-93" aria-hidden="true" tabindex="-1"></a>|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|</span>
<span id="cb13-94"><a href="#cb13-94" aria-hidden="true" tabindex="-1"></a>| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 |</span>
<span id="cb13-95"><a href="#cb13-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-96"><a href="#cb13-96" aria-hidden="true" tabindex="-1"></a>The modulo-26 operation guarantees that the result always stays within the valid range: when the sum exceeds 25, the remainder of division by 26 brings it back into the alphabet. For example, encrypting the letter "y" ($p = 24$) with $k = 3$: $C = (24 + 3) \bmod 26 = 27 \bmod 26 = 1$, which corresponds to the letter "B".</span>
<span id="cb13-97"><a href="#cb13-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-98"><a href="#cb13-98" aria-hidden="true" tabindex="-1"></a>**Key space and brute force.** The key $k$ can only take 25 distinct values (excluding $k = 0$, which encrypts nothing, and $k = 26$, equivalent to $k = 0$). Such a small key space makes the Caesar cipher trivially vulnerable to a brute-force attack: simply generate all 25 candidate decryptions and identify the one that is intelligible.</span>
<span id="cb13-99"><a href="#cb13-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-100"><a href="#cb13-100" aria-hidden="true" tabindex="-1"></a>**Cryptanalysis by frequency analysis.** Even without resorting to brute force, the Caesar cipher is easily broken by cryptanalysis, by exploiting two sources of information: the structure of the text (spaces between words survive encryption, revealing the length of each word) and the language of the plaintext (allowing a search for patterns of short, frequent words, such as "to", "be", "as", "is", "it", "the"). Combining these clues with the relative frequency of each letter, which in a natural language is far from uniform, a cryptanalyst can typically recover the key within a few minutes <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>.</span>
<span id="cb13-101"><a href="#cb13-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-102"><a href="#cb13-102" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb13-103"><a href="#cb13-103" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Why it is so easy to break</span></span>
<span id="cb13-104"><a href="#cb13-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-105"><a href="#cb13-105" aria-hidden="true" tabindex="-1"></a>The ease of the cryptanalysis lies not only in the algorithm itself, but in the fact that the attacker has access to far more information than just the algorithm and the ciphertext: they know the language of the message and its structure (where words begin and end). Hiding that structure, by removing the spaces from the ciphertext, makes a manual attack harder, but not impossible: other statistical features of the language, such as the frequency of consecutive letter pairs, remain available.</span>
<span id="cb13-106"><a href="#cb13-106" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-107"><a href="#cb13-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-108"><a href="#cb13-108" aria-hidden="true" tabindex="-1"></a>**Worked exercise: cryptanalysis via digraphs and trigraphs.** A short word that repeats in the message, as a separate, complete word, always produces the same block of letters in the ciphertext, since the Caesar cipher applies a fixed shift. Consider the following ciphertext <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-109"><a href="#cb13-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-110"><a href="#cb13-110" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-111"><a href="#cb13-111" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-112"><a href="#cb13-112" aria-hidden="true" tabindex="-1"></a><span class="in">Ciphertext:  YT GJ TW STY YT GJ YMFY NX YMJ VZJXYNTS</span></span>
<span id="cb13-113"><a href="#cb13-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-114"><a href="#cb13-114" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-115"><a href="#cb13-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-116"><a href="#cb13-116" aria-hidden="true" tabindex="-1"></a>The text has two blocks that repeat, each one twice: **YT** and **GJ**. In English, "to" is one of the most common two-letter words, and "the" one of the most common three-letter words. A natural first guess is that "YT" corresponds to "to"; trying that hypothesis against the rest of the ciphertext already reveals a partial, encouraging pattern. Adding the guess that a further three-letter block corresponds to "the" completes the picture. Assuming that YT corresponds to "TO" and the block YMJ to "THE":</span>
<span id="cb13-117"><a href="#cb13-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-118"><a href="#cb13-118" aria-hidden="true" tabindex="-1"></a>$$k = (\text{Y} - \text{T}) \bmod 26 = (24 - 19) \bmod 26 = 5$$</span>
<span id="cb13-119"><a href="#cb13-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-120"><a href="#cb13-120" aria-hidden="true" tabindex="-1"></a>Note that it is essential for "to" and "the" to appear as separate words, never embedded inside a larger word, since only a repeated, isolated word guarantees an identical block of ciphertext.</span>
<span id="cb13-121"><a href="#cb13-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-122"><a href="#cb13-122" aria-hidden="true" tabindex="-1"></a>With $k = 5$ known, the rest of the text decrypts immediately, word by word:</span>
<span id="cb13-123"><a href="#cb13-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-124"><a href="#cb13-124" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-125"><a href="#cb13-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-126"><a href="#cb13-126" aria-hidden="true" tabindex="-1"></a><span class="in">Plaintext:  TO BE OR NOT TO BE THAT IS THE QUESTION</span></span>
<span id="cb13-127"><a href="#cb13-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-128"><a href="#cb13-128" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-129"><a href="#cb13-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-130"><a href="#cb13-130" aria-hidden="true" tabindex="-1"></a>"To be, or not to be, that is the question" — the opening line of Hamlet's soliloquy, from Shakespeare's *Hamlet* (Act 3, Scene 1).</span>
<span id="cb13-131"><a href="#cb13-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-132"><a href="#cb13-132" aria-hidden="true" tabindex="-1"></a>::::: {.callout-tip}</span>
<span id="cb13-133"><a href="#cb13-133" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Exercise: break it yourself</span></span>
<span id="cb13-134"><a href="#cb13-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-135"><a href="#cb13-135" aria-hidden="true" tabindex="-1"></a>Applying the same technique, break the following ciphertext (this time with no spaces between words):</span>
<span id="cb13-136"><a href="#cb13-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-137"><a href="#cb13-137" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-138"><a href="#cb13-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-139"><a href="#cb13-139" aria-hidden="true" tabindex="-1"></a><span class="in">JUURBFNUUCQJCNWMBFNUU</span></span>
<span id="cb13-140"><a href="#cb13-140" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-141"><a href="#cb13-141" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-142"><a href="#cb13-142" aria-hidden="true" tabindex="-1"></a>:::::</span>
<span id="cb13-143"><a href="#cb13-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-144"><a href="#cb13-144" aria-hidden="true" tabindex="-1"></a><span class="fu">### The monoalphabetic cipher {#sec-01-monoalfabetica}</span></span>
<span id="cb13-145"><a href="#cb13-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-146"><a href="#cb13-146" aria-hidden="true" tabindex="-1"></a>The Caesar cipher is a very restricted special case of a more general class: the **monoalphabetic cipher**, in which the key is an arbitrary permutation of the 26 letters of the alphabet, not merely a fixed shift. The key space grows from 25 to $26! \approx 4 \times 10^{26}$, making a brute-force attack computationally infeasible. For example:</span>
<span id="cb13-147"><a href="#cb13-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-148"><a href="#cb13-148" aria-hidden="true" tabindex="-1"></a>| A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z |</span>
<span id="cb13-149"><a href="#cb13-149" aria-hidden="true" tabindex="-1"></a>|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|</span>
<span id="cb13-150"><a href="#cb13-150" aria-hidden="true" tabindex="-1"></a>| J | G | I | U | Z | M | V | B | L | X | W | C | E | D | H | Y | T | K | Q | N | P | R | A | F | S | O |</span>
<span id="cb13-151"><a href="#cb13-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-152"><a href="#cb13-152" aria-hidden="true" tabindex="-1"></a>Despite the astronomically larger key space, the monoalphabetic cipher remains vulnerable to cryptanalysis by frequency analysis: since each plaintext letter always corresponds to the same ciphertext letter, the statistical distribution of the plaintext letters carries over, intact, into the ciphertext, with only the symbols swapped. Comparing the frequency of the letters in the ciphertext with the known letter frequencies of the plaintext's language is enough to reconstruct much of the correspondence, even without ever recovering the full permutation directly.</span>
<span id="cb13-153"><a href="#cb13-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-154"><a href="#cb13-154" aria-hidden="true" tabindex="-1"></a>In English, the distribution of letters is far from uniform: E, T and A clearly dominate, followed by an intermediate group (O, I, N, S, H, R, D, L), and a set of rare letters (above all J, X, Q, Z, virtually absent as anything but the rare, distinctive appearance):</span>
<span id="cb13-155"><a href="#cb13-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-156"><a href="#cb13-156" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">Letter frequency in English, as standardly published in the cryptographic literature [@Stallings2020].</span><span class="co">](../assets/images/fig-frequencia-letras-en.png)</span>{#fig-01-frequencia-letras}</span>
<span id="cb13-157"><a href="#cb13-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-158"><a href="#cb13-158" aria-hidden="true" tabindex="-1"></a>**Worked exercise: a classic ciphertext.** Consider the following ciphertext, 120 letters long, encrypted with a single, fixed monoalphabetic substitution <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-159"><a href="#cb13-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-160"><a href="#cb13-160" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-161"><a href="#cb13-161" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-162"><a href="#cb13-162" aria-hidden="true" tabindex="-1"></a><span class="in">UZQSOVUOHXMOPVGPOZPEVSGZWSZOPFPESXUDBMETSXAIZ</span></span>
<span id="cb13-163"><a href="#cb13-163" aria-hidden="true" tabindex="-1"></a><span class="in">VUEPHZHMDZSHZOWSFPAPPDTSVPQUZWYMXUZUHSX</span></span>
<span id="cb13-164"><a href="#cb13-164" aria-hidden="true" tabindex="-1"></a><span class="in">EPYEPOPDZSZUFPOMBZWPFUPZHMDJUDTMOHMQ</span></span>
<span id="cb13-165"><a href="#cb13-165" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-166"><a href="#cb13-166" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-167"><a href="#cb13-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-168"><a href="#cb13-168" aria-hidden="true" tabindex="-1"></a>Counting the letters of this ciphertext gives the following frequency table (the most frequent letters only):</span>
<span id="cb13-169"><a href="#cb13-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-170"><a href="#cb13-170" aria-hidden="true" tabindex="-1"></a>| Ciphertext letter | Observed frequency |</span>
<span id="cb13-171"><a href="#cb13-171" aria-hidden="true" tabindex="-1"></a>|:-:|:-:|</span>
<span id="cb13-172"><a href="#cb13-172" aria-hidden="true" tabindex="-1"></a>| P | 13.33% |</span>
<span id="cb13-173"><a href="#cb13-173" aria-hidden="true" tabindex="-1"></a>| Z | 11.67% |</span>
<span id="cb13-174"><a href="#cb13-174" aria-hidden="true" tabindex="-1"></a>| S | 8.33% |</span>
<span id="cb13-175"><a href="#cb13-175" aria-hidden="true" tabindex="-1"></a>| U | 8.33% |</span>
<span id="cb13-176"><a href="#cb13-176" aria-hidden="true" tabindex="-1"></a>| O | 7.50% |</span>
<span id="cb13-177"><a href="#cb13-177" aria-hidden="true" tabindex="-1"></a>| M | 6.67% |</span>
<span id="cb13-178"><a href="#cb13-178" aria-hidden="true" tabindex="-1"></a>| H | 5.83% |</span>
<span id="cb13-179"><a href="#cb13-179" aria-hidden="true" tabindex="-1"></a>| D | 5.00% |</span>
<span id="cb13-180"><a href="#cb13-180" aria-hidden="true" tabindex="-1"></a>| E | 5.00% |</span>
<span id="cb13-181"><a href="#cb13-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-182"><a href="#cb13-182" aria-hidden="true" tabindex="-1"></a>Comparing this table with the reference chart (@fig-01-frequencia-letras): P, the most frequent ciphertext letter by a wide margin, is the natural candidate for E (12.7%), the most frequent letter of English; Z, the second most frequent, is the natural candidate for T (9.1%), the second most frequent letter of the language — a direct and safe correspondence, because the gap between these two values and the third-placed letter is wide enough to leave no doubt. From here, however, direct correspondence stops being reliable: both the ciphertext and the reference chart have several values that are close together or effectively tied from the 3rd position onward (8.33% vs. 8.33%; 5.00% vs. 5.00%; 4.17% vs. 4.17%), and with only 120 letters these small differences carry little statistical weight. Matching position by position, purely mechanically, with no other clue:</span>
<span id="cb13-183"><a href="#cb13-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-184"><a href="#cb13-184" aria-hidden="true" tabindex="-1"></a>| # | Ciphertext | English ref. | Direct guess | Real key | Hit? |</span>
<span id="cb13-185"><a href="#cb13-185" aria-hidden="true" tabindex="-1"></a>|:-:|:-:|:-:|:-:|:-:|:-:|</span>
<span id="cb13-186"><a href="#cb13-186" aria-hidden="true" tabindex="-1"></a>| 1 | P (13.33%) | E (12.70%) | P→E | P→E | yes |</span>
<span id="cb13-187"><a href="#cb13-187" aria-hidden="true" tabindex="-1"></a>| 2 | Z (11.67%) | T (9.06%) | Z→T | Z→T | yes |</span>
<span id="cb13-188"><a href="#cb13-188" aria-hidden="true" tabindex="-1"></a>| 3 | U (8.33%) | A (8.17%) | U→A | U→I | no |</span>
<span id="cb13-189"><a href="#cb13-189" aria-hidden="true" tabindex="-1"></a>| 4 | S (8.33%) | O (7.51%) | S→O | S→A | no |</span>
<span id="cb13-190"><a href="#cb13-190" aria-hidden="true" tabindex="-1"></a>| 5 | O (7.50%) | I (6.97%) | O→I | O→S | no |</span>
<span id="cb13-191"><a href="#cb13-191" aria-hidden="true" tabindex="-1"></a>| 6 | M (6.67%) | N (6.75%) | M→N | M→O | no |</span>
<span id="cb13-192"><a href="#cb13-192" aria-hidden="true" tabindex="-1"></a>| 7 | H (5.83%) | S (6.33%) | H→S | H→C | no |</span>
<span id="cb13-193"><a href="#cb13-193" aria-hidden="true" tabindex="-1"></a>| 8 | E (5.00%) | H (6.09%) | E→H | E→R | no |</span>
<span id="cb13-194"><a href="#cb13-194" aria-hidden="true" tabindex="-1"></a>| 9 | D (5.00%) | R (5.99%) | D→R | D→N | no |</span>
<span id="cb13-195"><a href="#cb13-195" aria-hidden="true" tabindex="-1"></a>| 10 | V (4.17%) | D (4.25%) | V→D | V→D | yes |</span>
<span id="cb13-196"><a href="#cb13-196" aria-hidden="true" tabindex="-1"></a>| 11 | X (4.17%) | L (4.03%) | X→L | X→L | yes |</span>
<span id="cb13-197"><a href="#cb13-197" aria-hidden="true" tabindex="-1"></a>| 12 | W (3.33%) | C (2.78%) | W→C | W→H | no |</span>
<span id="cb13-198"><a href="#cb13-198" aria-hidden="true" tabindex="-1"></a>| 13 | F (3.33%) | U (2.76%) | F→U | F→V | no |</span>
<span id="cb13-199"><a href="#cb13-199" aria-hidden="true" tabindex="-1"></a>| 14 | Q (2.50%) | M (2.41%) | Q→M | Q→W | no |</span>
<span id="cb13-200"><a href="#cb13-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-201"><a href="#cb13-201" aria-hidden="true" tabindex="-1"></a>Only 4 of these 14 correspondences (29%) coincide with the real key, and the mismatches start right after the dominant pair. This is not a weakness of this particular example: it is the realistic situation for any intercepted message of moderate length. Frequency analysis alone never fully decrypts a message on its own; it only narrows the field for the most and least common letters, leaving most of the alphabet unresolved.</span>
<span id="cb13-202"><a href="#cb13-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-203"><a href="#cb13-203" aria-hidden="true" tabindex="-1"></a>**Digraphs and trigraphs, once more.** To go further, the cryptanalyst falls back on the technique already used above with "to" and "the": look for blocks of letters that repeat in the ciphertext, and test them against short, frequent words or word fragments of the language. Because this is a simple substitution, a repeated sequence of letters produces the same ciphertext block wherever it occurs — even when the repetition straddles a word boundary rather than reproducing a whole word. Counting the 3- to 5-letter blocks that repeat across the 120 letters of ciphertext, one stands out immediately: **ZHMD**, which occurs twice.</span>
<span id="cb13-204"><a href="#cb13-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-205"><a href="#cb13-205" aria-hidden="true" tabindex="-1"></a>Since Z is already known to correspond to T, a natural hypothesis is that ZHMD begins a word starting with "T". A second repeated block, **DZS** (also twice), shares the same D and Z, and decodes consistently as "...NTA..." once D is guessed as N — exactly the pattern found inside "co**nta**cts" and "represe**nta**tives". Testing ZHMD as "TCON" — the fragment shared by "direc**TCON**tacts" and "vie**TCON**g" — fits both repeated occurrences perfectly and yields three new letters at once: H→C, M→O, D→N. Combined with S→A (confirmed by the "NTA" pattern) and the two already known (P→E, Z→T), six letters of the key are now fixed without any brute force. Applying them to the ciphertext already makes the message legible in patches:</span>
<span id="cb13-206"><a href="#cb13-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-207"><a href="#cb13-207" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-208"><a href="#cb13-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-209"><a href="#cb13-209" aria-hidden="true" tabindex="-1"></a><span class="in">...UEPHZHMDZSHZOWSFPAPPDTSVPQUZWYMXUZUHSX...</span></span>
<span id="cb13-210"><a href="#cb13-210" aria-hidden="true" tabindex="-1"></a><span class="in">...___ECTCONTACT__A_E_EEN_A_E__T__O__T_CA_...</span></span>
<span id="cb13-211"><a href="#cb13-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-212"><a href="#cb13-212" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-213"><a href="#cb13-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-214"><a href="#cb13-214" aria-hidden="true" tabindex="-1"></a>"<span class="sc">\_\_</span>ECT CONTACT<span class="sc">\_\_</span>A<span class="sc">\_</span>E <span class="sc">\_</span>EEN <span class="sc">\_</span>A<span class="sc">\_</span>E <span class="sc">\_\_</span>T<span class="sc">\_</span> <span class="sc">\_</span>O<span class="sc">\_\_</span>T<span class="sc">\_</span>CA<span class="sc">\_</span>" is already unmistakably "...irect contacts have been made with...ical...". The remaining gaps close by vocabulary, exactly as before, revealing the full sentence:</span>
<span id="cb13-215"><a href="#cb13-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-216"><a href="#cb13-216" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "It was disclosed yesterday that several informal but direct contacts have been made with political representatives of the Viet Cong in Moscow."</span></span>
<span id="cb13-217"><a href="#cb13-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-218"><a href="#cb13-218" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb13-219"><a href="#cb13-219" aria-hidden="true" tabindex="-1"></a><span class="fu">#### What if the ciphertext kept the spaces?</span></span>
<span id="cb13-220"><a href="#cb13-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-221"><a href="#cb13-221" aria-hidden="true" tabindex="-1"></a>If word boundaries were visible, the attack would change shape again. This particular sentence has no single-letter words, and none of its three short words repeats (**IT**, **OF**, **IN**; **WAS**, **BUT**, **THE**). But spaces still help decisively: once the dominant pair P→E and Z→T is known, a 3-letter word beginning with Z and ending in P is almost certainly "the" — by far the most common three-letter word in English — without needing to search the ciphertext for any hidden repetition. Here that word is ciphered as "ZWP", so that single, targeted test gives W→H immediately, a letter the boundary-spanning "TCON" crib above never touched.</span>
<span id="cb13-222"><a href="#cb13-222" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-223"><a href="#cb13-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-224"><a href="#cb13-224" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Playfair cipher {#sec-01-playfair}</span></span>
<span id="cb13-225"><a href="#cb13-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-226"><a href="#cb13-226" aria-hidden="true" tabindex="-1"></a>The Playfair cipher reduces the problem above by encrypting **pairs of letters** (digraphs), rather than isolated letters, using a $5 \times 5$ grid built from a keyword. By encrypting pairs instead of individual letters, the frequency distribution of isolated letters no longer carries over directly into the ciphertext, making simple frequency analysis harder.</span>
<span id="cb13-227"><a href="#cb13-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-228"><a href="#cb13-228" aria-hidden="true" tabindex="-1"></a>**Building the grid.** A keyword is chosen, its letters (without repetitions) are written into the first positions of the grid, and the remaining positions are filled with the letters of the alphabet in order, skipping those already used. Since the grid has only 25 positions for 26 letters, "I" and "J" share the same cell. With the keyword "ESIGELEC" (a partner's French Engineering School), after removing its repeated letters:</span>
<span id="cb13-229"><a href="#cb13-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-230"><a href="#cb13-230" aria-hidden="true" tabindex="-1"></a><span class="al">![Playfair grid built from the keyword "ESIGELEC".](../assets/images/fig-playfair-grelha-en.png)</span>{#fig-01-playfair-grelha width=44%}</span>
<span id="cb13-231"><a href="#cb13-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-232"><a href="#cb13-232" aria-hidden="true" tabindex="-1"></a>**Encryption rules**, applied to each pair of plaintext letters:</span>
<span id="cb13-233"><a href="#cb13-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-234"><a href="#cb13-234" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>If the two letters are in the **same row**, each is replaced by the letter immediately to its right (wrapping around to the start of the row, if necessary).</span>
<span id="cb13-235"><a href="#cb13-235" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>If the two letters are in the **same column**, each is replaced by the letter immediately below it (wrapping around to the top, if necessary).</span>
<span id="cb13-236"><a href="#cb13-236" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Otherwise, each letter is replaced by the letter on its own row, but in the column of the other letter (the two letters and their replacements form a rectangle in the grid).</span>
<span id="cb13-237"><a href="#cb13-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-238"><a href="#cb13-238" aria-hidden="true" tabindex="-1"></a>If the two letters of a pair are identical, or if a single letter is left over at the end of a text with an odd number of letters, a filler letter is inserted (here, "X").</span>
<span id="cb13-239"><a href="#cb13-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-240"><a href="#cb13-240" aria-hidden="true" tabindex="-1"></a>Consider the phrase "ALL IS WELL". Without spaces, and split into pairs (a repeated letter within a pair is separated with a filler "X"):</span>
<span id="cb13-241"><a href="#cb13-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-242"><a href="#cb13-242" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-243"><a href="#cb13-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-244"><a href="#cb13-244" aria-hidden="true" tabindex="-1"></a><span class="in">AL LI SW EL LX</span></span>
<span id="cb13-245"><a href="#cb13-245" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-246"><a href="#cb13-246" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-247"><a href="#cb13-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-248"><a href="#cb13-248" aria-hidden="true" tabindex="-1"></a>Applying the rules: "AL" shares no row or column, so the rectangle rule gives FS. "LI" is in the same row, giving EG. "SW" is in the same column, giving AS. "EL" is in the same row, giving SE. "LX" shares no row or column, giving IZ. The final ciphertext:</span>
<span id="cb13-249"><a href="#cb13-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-250"><a href="#cb13-250" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-251"><a href="#cb13-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-252"><a href="#cb13-252" aria-hidden="true" tabindex="-1"></a><span class="in">FSEGASSEIZ</span></span>
<span id="cb13-253"><a href="#cb13-253" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-254"><a href="#cb13-254" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-255"><a href="#cb13-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-256"><a href="#cb13-256" aria-hidden="true" tabindex="-1"></a>Even so, Playfair remains vulnerable: the frequency distribution of letter pairs (digraphs) in a natural language is likewise non-uniform, and this asymmetry survives encryption in a manner analogous to that of isolated letters. A cryptanalyst with enough ciphertext can reconstruct the grid through digraph frequency analysis.</span>
<span id="cb13-257"><a href="#cb13-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-258"><a href="#cb13-258" aria-hidden="true" tabindex="-1"></a><span class="fu">### Polyalphabetic cipher: Vigenère {#sec-01-vigenere}</span></span>
<span id="cb13-259"><a href="#cb13-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-260"><a href="#cb13-260" aria-hidden="true" tabindex="-1"></a>The ciphers above share a structural weakness: each plaintext letter always corresponds to the same letter (or pair of letters) in the ciphertext, throughout the whole message. **Polyalphabetic ciphers** remove this fixed correspondence, using several different substitutions across the text, cycled according to a keyword that repeats itself.</span>
<span id="cb13-261"><a href="#cb13-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-262"><a href="#cb13-262" aria-hidden="true" tabindex="-1"></a>In the Vigenère cipher, the keyword defines a sequence of shifts (each letter of the key corresponds to a different Caesar shift), applied cyclically to the successive letters of the plaintext. With $m$ the length of the keyword, and $k_0, k_1, \dots, k_{m-1}$ the shifts it defines:</span>
<span id="cb13-263"><a href="#cb13-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-264"><a href="#cb13-264" aria-hidden="true" tabindex="-1"></a>$$C_i = (p_i + k_{i \bmod m}) \bmod 26 \qquad p_i = (C_i - k_{i \bmod m}) \bmod 26$$</span>
<span id="cb13-265"><a href="#cb13-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-266"><a href="#cb13-266" aria-hidden="true" tabindex="-1"></a>Since the key is shorter than the message ($m$ is typically much smaller than the number of plaintext letters), the index $i \bmod m$ makes it repeat cyclically until it covers the whole text. The same plaintext letter can thus correspond to different ciphertext letters, depending on the position at which it occurs, which considerably flattens the frequency distribution observable in the ciphertext.</span>
<span id="cb13-267"><a href="#cb13-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-268"><a href="#cb13-268" aria-hidden="true" tabindex="-1"></a>@fig-01-achatamento-frequencia shows this effect directly: for each cipher, the ciphertext letters are ranked from most to least frequent and normalised against the most common letter's frequency. Plaintext produces a steeply sloped curve, with a small number of letters dominating. Playfair flattens it moderately, by substituting pairs of letters rather than single letters. Vigenère flattens it further still, precisely through the mechanism described above. A polyalphabetic cipher with a key as long as it is (pseudo)random approaches a nearly horizontal line, with no letter standing out at all — that is the line the One-Time Pad, further ahead, reaches perfectly.</span>
<span id="cb13-269"><a href="#cb13-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-270"><a href="#cb13-270" aria-hidden="true" tabindex="-1"></a><span class="al">![Flattening of the frequency distribution: as a cipher approaches the ideal polyalphabetic case, the ranked-frequency curve becomes flatter, eliminating the statistical information that frequency cryptanalysis would exploit.](../assets/images/fig-01-achatamento-frequencia.png)</span>{#fig-01-achatamento-frequencia width=70%}</span>
<span id="cb13-271"><a href="#cb13-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-272"><a href="#cb13-272" aria-hidden="true" tabindex="-1"></a>Using the keyword "deceptive" and the plaintext "we are discovered save yourself" <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>:</span>
<span id="cb13-273"><a href="#cb13-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-274"><a href="#cb13-274" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-275"><a href="#cb13-275" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-276"><a href="#cb13-276" aria-hidden="true" tabindex="-1"></a><span class="in">Key:         D E C E P T I V E D E C E P T I V E D E C E P T I V E</span></span>
<span id="cb13-277"><a href="#cb13-277" aria-hidden="true" tabindex="-1"></a><span class="in">Plaintext:   W E A R E D I S C O V E R E D S A V E Y O U R S E L F</span></span>
<span id="cb13-278"><a href="#cb13-278" aria-hidden="true" tabindex="-1"></a><span class="in">Ciphertext:  Z I C V T W Q N G R Z G V T W A V Z H C Q Y G L M G J</span></span>
<span id="cb13-279"><a href="#cb13-279" aria-hidden="true" tabindex="-1"></a><span class="in">                    ^ ^ ^                 ^ ^ ^</span></span>
<span id="cb13-280"><a href="#cb13-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-281"><a href="#cb13-281" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-282"><a href="#cb13-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-283"><a href="#cb13-283" aria-hidden="true" tabindex="-1"></a>Notice the block **VTW**, which appears twice in the ciphertext, 9 positions apart. This is not a repeated word this time, it is a genuine coincidence of the plaintext itself: the sequence "red" appears once spanning the boundary between "wea**re**" and "**d**iscovered", and again inside "disco**vered**" itself, exactly 9 letters later. Since the keyword "deceptive" also has 9 letters, both occurrences of "red" align with the key in exactly the same way, producing the same ciphertext block. This is the principle behind the Kasiski examination: whenever a stretch of plaintext repeats at a distance that is a multiple of the key length, even by coincidence, the corresponding ciphertext repeats too, and that visible repetition is a direct clue to the length of the key, here, 9.</span>
<span id="cb13-284"><a href="#cb13-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-285"><a href="#cb13-285" aria-hidden="true" tabindex="-1"></a>The Vigenère cipher resisted systematic cryptanalysis for centuries, but it is not unbreakable: if the key is short and repeated many times over a sufficiently long text, techniques such as the Kasiski examination (identifying repetitions in the ciphertext, which reveal multiples of the key length) allow the key length to be recovered, and from there the text can be treated as several independent Caesar ciphers, one for each position within the key's cycle.</span>
<span id="cb13-286"><a href="#cb13-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-287"><a href="#cb13-287" aria-hidden="true" tabindex="-1"></a>Knowing already, from the Kasiski examination alone, that the key has 9 letters (without yet knowing which ones), the cryptanalyst regroups the ciphertext: all the letters in positions 1, 10, 19, ... form a first group; positions 2, 11, 20, ... form a second group; and so on up to the ninth group. Each group, taken in isolation, is an ordinary Caesar cipher, with a single fixed $k$, exactly the kind of problem already solved in the previous section:</span>
<span id="cb13-288"><a href="#cb13-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-289"><a href="#cb13-289" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-290"><a href="#cb13-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-291"><a href="#cb13-291" aria-hidden="true" tabindex="-1"></a><span class="in">Group 1 (pos. 1, 10, 19):  Z R H</span></span>
<span id="cb13-292"><a href="#cb13-292" aria-hidden="true" tabindex="-1"></a><span class="in">Group 2 (pos. 2, 11, 20):  I Z C</span></span>
<span id="cb13-293"><a href="#cb13-293" aria-hidden="true" tabindex="-1"></a><span class="in">Group 3 (pos. 3, 12, 21):  C G Q</span></span>
<span id="cb13-294"><a href="#cb13-294" aria-hidden="true" tabindex="-1"></a><span class="in">Group 4 (pos. 4, 13, 22):  V V Y</span></span>
<span id="cb13-295"><a href="#cb13-295" aria-hidden="true" tabindex="-1"></a><span class="in">Group 5 (pos. 5, 14, 23):  T T G</span></span>
<span id="cb13-296"><a href="#cb13-296" aria-hidden="true" tabindex="-1"></a><span class="in">Group 6 (pos. 6, 15, 24):  W W L</span></span>
<span id="cb13-297"><a href="#cb13-297" aria-hidden="true" tabindex="-1"></a><span class="in">Group 7 (pos. 7, 16, 25):  Q A M</span></span>
<span id="cb13-298"><a href="#cb13-298" aria-hidden="true" tabindex="-1"></a><span class="in">Group 8 (pos. 8, 17, 26):  N V G</span></span>
<span id="cb13-299"><a href="#cb13-299" aria-hidden="true" tabindex="-1"></a><span class="in">Group 9 (pos. 9, 18, 27):  G Z J</span></span>
<span id="cb13-300"><a href="#cb13-300" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-301"><a href="#cb13-301" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-302"><a href="#cb13-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-303"><a href="#cb13-303" aria-hidden="true" tabindex="-1"></a>Note that this does not contradict what was said above about Vigenère flattening the frequency distribution: that distortion affects the ciphertext *as a whole*, where letters encrypted with different shifts are mixed together. Within each isolated group, however, the same shift was always used, so the distribution reverts to that of an ordinary Caesar cipher, with no flattening at all. The Kasiski examination and frequency analysis therefore solve two different, complementary problems: one gives the number of groups to form (the key length); the other, applied afterwards to each group separately, gives the shift of each one.</span>
<span id="cb13-304"><a href="#cb13-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-305"><a href="#cb13-305" aria-hidden="true" tabindex="-1"></a>To each group is applied, in isolation, the same single-letter frequency analysis used against the Caesar cipher: which is the most frequent letter of this group, and which letter of the language should it correspond to? In this example, with only 3 letters per group, there is not enough data for that analysis to be reliable; in a real, considerably longer text, each group would have dozens or hundreds of letters, and the method would work just as well as it did against the Caesar cipher.</span>
<span id="cb13-306"><a href="#cb13-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-307"><a href="#cb13-307" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Vernam cipher {#sec-01-vernam}</span></span>
<span id="cb13-308"><a href="#cb13-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-309"><a href="#cb13-309" aria-hidden="true" tabindex="-1"></a>Before reaching the definitive solution, it is worth taking one intermediate step. The **Vernam cipher**, created by Gilbert Vernam at AT&amp;T laboratories in 1918 for telegraphy [@Stallings2020], generalises Vigenère in two ways: it replaces modular addition with a bitwise **XOR** operation, and it uses a key much longer than the short keyword typical of Vigenère, to the point of being, in practice, as long as the punched paper tape that implemented it.</span>
<span id="cb13-310"><a href="#cb13-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-311"><a href="#cb13-311" aria-hidden="true" tabindex="-1"></a>$$C_i = P_i \oplus K_{i \bmod m} \qquad P_i = C_i \oplus K_{i \bmod m}$$</span>
<span id="cb13-312"><a href="#cb13-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-313"><a href="#cb13-313" aria-hidden="true" tabindex="-1"></a><span class="al">![The Vernam cipher: a keystream generator produces the sequence $k_i$, combined by XOR with the plaintext during encryption, and with the ciphertext during decryption — the same operation in both directions.](../assets/images/fig-vernam-gerador-en.png)</span>{#fig-01-vernam-gerador width=95%}</span>
<span id="cb13-314"><a href="#cb13-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-315"><a href="#cb13-315" aria-hidden="true" tabindex="-1"></a>A much longer key considerably hinders the Kasiski examination, since repetitions in the ciphertext become much rarer. But the underlying problem does not disappear: sooner or later, even a very long key tape runs out and has to start again, reintroducing a cycle, albeit a much larger one than a Vigenère keyword's. The Vernam cipher is therefore a substantial improvement over Vigenère, but not a definitive solution: it remains vulnerable, in principle, to the same kind of cryptanalysis, only requiring much longer intercepted messages to become practicable.</span>
<span id="cb13-316"><a href="#cb13-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-317"><a href="#cb13-317" aria-hidden="true" tabindex="-1"></a>Note a structural limitation of the Vernam cipher as originally conceived: it uses only a key, with no other value to distinguish one message from the next. It is precisely this absence that forces the key tape to repeat once it runs out. Modern stream ciphers, taken up again in Chapter 4, solve this problem by introducing a second value, the *nonce*, unique per message but not secret, which allows the same key to be reused safely from message to message, without ever repeating the keystream.</span>
<span id="cb13-318"><a href="#cb13-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-319"><a href="#cb13-319" aria-hidden="true" tabindex="-1"></a><span class="fu">### The One-Time Pad {#sec-01-otp}</span></span>
<span id="cb13-320"><a href="#cb13-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-321"><a href="#cb13-321" aria-hidden="true" tabindex="-1"></a>The **One-Time Pad** definitively resolves the weakness that the Vernam cipher only mitigated: it uses a genuinely random key, the same length as the message, never reused for another message, and therefore never subject to any cycle at all. Each plaintext letter is combined with the corresponding key letter, just as in Vigenère, but without any cycle, since the key is exactly as long as the text itself.</span>
<span id="cb13-322"><a href="#cb13-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-323"><a href="#cb13-323" aria-hidden="true" tabindex="-1"></a>Claude Shannon proved, in 1949, that the One-Time Pad, when used correctly, is **mathematically unbreakable**: the ciphertext reveals no information whatsoever about the plaintext, even with unlimited computational power [@Shannon1949]. This property is called **perfect secrecy**.</span>
<span id="cb13-324"><a href="#cb13-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-325"><a href="#cb13-325" aria-hidden="true" tabindex="-1"></a>**A concrete example of perfect secrecy.** For any ciphertext $C$ and any plaintext $P$ of the same length, there is always exactly one key $K = (C - P) \bmod 26$ linking them. Since every key is, a priori, equally likely, the ciphertext does not favour any one reading over another: for a given ciphertext, there is always some key that decrypts it into any plaintext one likes, of the same length.</span>
<span id="cb13-326"><a href="#cb13-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-327"><a href="#cb13-327" aria-hidden="true" tabindex="-1"></a>This can be demonstrated concretely. Fixing a single 22-letter ciphertext, three different keys decrypt it into three plausible, mutually exclusive solutions:</span>
<span id="cb13-328"><a href="#cb13-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-329"><a href="#cb13-329" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-330"><a href="#cb13-330" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-331"><a href="#cb13-331" aria-hidden="true" tabindex="-1"></a><span class="in">Ciphertext (fixed):    G L S P A J H V I H O Q Z P L U F S V A K O</span></span>
<span id="cb13-332"><a href="#cb13-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-333"><a href="#cb13-333" aria-hidden="true" tabindex="-1"></a><span class="in">Key 1: U D A X I H H E X D V X R C S N B A C G H Q</span></span>
<span id="cb13-334"><a href="#cb13-334" aria-hidden="true" tabindex="-1"></a><span class="in">Decrypts to: MISS SCARLETT IN THE STUDY</span></span>
<span id="cb13-335"><a href="#cb13-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-336"><a href="#cb13-336" aria-hidden="true" tabindex="-1"></a><span class="in">Key 2: U U A A W J F H G X G D G I H J X R E A T Q</span></span>
<span id="cb13-337"><a href="#cb13-337" aria-hidden="true" tabindex="-1"></a><span class="in">Decrypts to: MRS PEACOCK IN THE LIBRARY</span></span>
<span id="cb13-338"><a href="#cb13-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-339"><a href="#cb13-339" aria-hidden="true" tabindex="-1"></a><span class="in">Key 3: E X H B N F W J O P V Q I M D H M L R X G B</span></span>
<span id="cb13-340"><a href="#cb13-340" aria-hidden="true" tabindex="-1"></a><span class="in">Decrypts to: COLONEL MUSTARD IN THE DEN</span></span>
<span id="cb13-341"><a href="#cb13-341" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-342"><a href="#cb13-342" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-343"><a href="#cb13-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-344"><a href="#cb13-344" aria-hidden="true" tabindex="-1"></a>All three decryptions are correct: each results from applying $p = (C - K) \bmod 26$, letter by letter, with the respective key. An attacker who intercepts only <span class="in">`GLSPAJHVIHOQZPLUFSVAKO`</span>, without knowing the key, has no way whatsoever of knowing whether the culprit is in the study, the library, or the den. These three readings, and infinitely many others of the same length, are all equally compatible with the ciphertext.</span>
<span id="cb13-345"><a href="#cb13-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-346"><a href="#cb13-346" aria-hidden="true" tabindex="-1"></a>Despite this absolute theoretical guarantee, the One-Time Pad is impractical in most real-world scenarios, for three requirements that are hard to satisfy simultaneously:</span>
<span id="cb13-347"><a href="#cb13-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-348"><a href="#cb13-348" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the key must be as long as the message;</span>
<span id="cb13-349"><a href="#cb13-349" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the key must be genuinely random, not generated by a deterministic algorithm;</span>
<span id="cb13-350"><a href="#cb13-350" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the key can never be reused, not even partially.</span>
<span id="cb13-351"><a href="#cb13-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-352"><a href="#cb13-352" aria-hidden="true" tabindex="-1"></a>Distributing and storing keys of this size, securely, is just as hard as securely distributing the message itself. There is also a less obvious cost: generating, in a genuinely random way, and then securely managing a large volume of keys of this size also carries a non-trivial computational cost, which can make the process too slow for most practical applications. These combined requirements limit the use of the One-Time Pad to very specific scenarios, such as certain diplomatic or military communications of exceptional importance.</span>
<span id="cb13-353"><a href="#cb13-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-354"><a href="#cb13-354" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Enigma machine {#sec-01-enigma}</span></span>
<span id="cb13-355"><a href="#cb13-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-356"><a href="#cb13-356" aria-hidden="true" tabindex="-1"></a>Enigma, used by Germany before and during the Second World War, is also a polyalphabetic cipher: as in Vigenère, the same plaintext letter corresponds to different ciphertext letters depending on the position at which it occurs. The difference lies in how that variation is generated. In Vigenère, a short keyword, repeated cyclically, determines the shift applied at each position; in Enigma, that role falls to a set of electromechanical **rotors** that advance one position with every keystroke, altering the electrical circuit that connects each input letter to its corresponding output letter. The effect is the same as in Vigenère (a different substitution at every position), but the "key length" before the cycle repeats grows from a handful of memorable letters to tens of thousands of positions — impractical to exploit through classical frequency analysis, though, unlike the One-Time Pad, far from mathematically unbreakable.</span>
<span id="cb13-357"><a href="#cb13-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-358"><a href="#cb13-358" aria-hidden="true" tabindex="-1"></a>It is important not to confuse the rotors with the key itself. Enigma's key, changed daily, was the set of settings that sender and receiver had to share in advance: which rotors to use and in what order, their initial position, the internal ring setting of each rotor, and the plugboard connections (which swapped pairs of letters before and after the rotors). The rotors do not generate this key: it is the key that determines how the rotors (and the plugboard) behave. What the rotors generate, mechanically, letter by letter, is the sequence of substitutions that this initial key sets in motion — the mechanical counterpart of the sequence of shifts that, in Vigenère, the keyword generates by repeating itself.</span>
<span id="cb13-359"><a href="#cb13-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-360"><a href="#cb13-360" aria-hidden="true" tabindex="-1"></a>Enigma was never broken by conventional frequency analysis: the period was far too long for any letter count to be useful. It was broken instead by a combination of a structural design flaw (the internal wiring guaranteed that no letter could ever be enciphered as itself, which eliminated hypotheses and made testing easier) and the very same probable-word ("*crib*") technique already used in this chapter: certain German messages almost always contained the same words in the same positions, such as the daily weather report ("*Wetterbericht*"), which allowed strong hypotheses about fragments of plaintext to be formed without any statistical analysis at all. Testing those hypotheses against the enormous space of possible settings, however, demanded an amount of computation impractical by hand; the Bombe, developed by Alan Turing and Gordon Welchman at Bletchley Park building on earlier mathematical work by Polish cryptanalysts <span class="co">[</span><span class="ot">@Rejewski1981</span><span class="co">]</span>, mechanised exactly that test at scale, anticipating many of the principles of the electronic computers that would follow <span class="co">[</span><span class="ot">@Kahn1967</span><span class="co">]</span>.</span>
<span id="cb13-361"><a href="#cb13-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-362"><a href="#cb13-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## Transposition Ciphers {#sec-01-transposicao}</span></span>
<span id="cb13-363"><a href="#cb13-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-364"><a href="#cb13-364" aria-hidden="true" tabindex="-1"></a>Unlike substitution ciphers, **transposition ciphers** do not change the identity of the plaintext symbols, only their order. The ciphertext contains exactly the same letters as the plaintext, merely rearranged according to a rule determined by the key.</span>
<span id="cb13-365"><a href="#cb13-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-366"><a href="#cb13-366" aria-hidden="true" tabindex="-1"></a><span class="fu">### The rail fence technique {#sec-01-rail-fence}</span></span>
<span id="cb13-367"><a href="#cb13-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-368"><a href="#cb13-368" aria-hidden="true" tabindex="-1"></a>The simplest form of transposition is the **rail fence** technique: the plaintext is written alternately across two lines, forming a zigzag, and the ciphertext is obtained by reading first the top line, then the bottom line, without interruption.</span>
<span id="cb13-369"><a href="#cb13-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-370"><a href="#cb13-370" aria-hidden="true" tabindex="-1"></a>For the plaintext "WE ARE DISCOVERED FLEE AT ONCE" (without spaces, 25 letters):</span>
<span id="cb13-371"><a href="#cb13-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-372"><a href="#cb13-372" aria-hidden="true" tabindex="-1"></a><span class="al">![The rail fence technique: the plaintext is written in a zigzag across two lines; the ciphertext is read line by line.](../assets/images/fig-rail-fence-en.png)</span>{#fig-01-rail-fence width=80%}</span>
<span id="cb13-373"><a href="#cb13-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-374"><a href="#cb13-374" aria-hidden="true" tabindex="-1"></a>Reading Line 1 followed by Line 2 gives the ciphertext <span class="in">`WAEICVRDLETNEERDSOEEFEAOC`</span>. Every letter of the ciphertext belongs to the plaintext, merely reordered, so statistical cryptanalysis based on isolated-letter frequency remains perfectly viable, as will be discussed further in this section.</span>
<span id="cb13-375"><a href="#cb13-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-376"><a href="#cb13-376" aria-hidden="true" tabindex="-1"></a><span class="fu">### Columnar transposition {#sec-01-transposicao-colunar}</span></span>
<span id="cb13-377"><a href="#cb13-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-378"><a href="#cb13-378" aria-hidden="true" tabindex="-1"></a>A more elaborate technique is **columnar transposition**: the plaintext is written into a grid with a number of columns equal to the length of the keyword, and the ciphertext is obtained by reading the columns in the alphabetical order of the keyword's letters, rather than the original order in which they were written.</span>
<span id="cb13-379"><a href="#cb13-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-380"><a href="#cb13-380" aria-hidden="true" tabindex="-1"></a>Consider the key <span class="in">`4312567`</span> and the plaintext "attack postponed until two am" <span class="co">[</span><span class="ot">@Stallings2020</span><span class="co">]</span>, padded with "xyz" to complete the final row (28 letters, arranged in four rows of seven columns):</span>
<span id="cb13-381"><a href="#cb13-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-382"><a href="#cb13-382" aria-hidden="true" tabindex="-1"></a><span class="al">![Columnar transposition grid with key 4312567. The digits above each column give the order in which the columns are read out.](../assets/images/fig-transposicao-grelha-en.png)</span>{#fig-01-transposicao-grelha width=68%}</span>
<span id="cb13-383"><a href="#cb13-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-384"><a href="#cb13-384" aria-hidden="true" tabindex="-1"></a>The ciphertext is obtained by reading the columns in the numerical order of their key digit (not the order in which they appear in the grid): first the column under key digit 1, then under digit 2, and so on up to the column under digit 7:</span>
<span id="cb13-385"><a href="#cb13-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-386"><a href="#cb13-386" aria-hidden="true" tabindex="-1"></a>::: {.httpmsg}</span>
<span id="cb13-387"><a href="#cb13-387" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-388"><a href="#cb13-388" aria-hidden="true" tabindex="-1"></a><span class="in">TTNAAPTMTSUOAODWCOIXKNLYPETZ</span></span>
<span id="cb13-389"><a href="#cb13-389" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb13-390"><a href="#cb13-390" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb13-391"><a href="#cb13-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-392"><a href="#cb13-392" aria-hidden="true" tabindex="-1"></a>Note that every letter of the plaintext is still present in the ciphertext, in the same quantity; only the order has changed.</span>
<span id="cb13-393"><a href="#cb13-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-394"><a href="#cb13-394" aria-hidden="true" tabindex="-1"></a>A single columnar transposition is vulnerable to cryptanalysis, since the frequency distribution of isolated letters remains entirely unchanged, only their relative position changes. There is an important difference here compared with substitution: in a substitution, frequency is used to guess which plaintext letter corresponds to each ciphertext letter, a mapping problem; in a transposition, there is no mapping to guess at all, since an "E" in the ciphertext really is an "E" from the original text, merely shifted in position. The most frequent letter of the ciphertext is, therefore, directly the most frequent letter of the language, with no intermediate hypothesis needed — which even makes it possible to **distinguish** a transposition from a substitution purely from frequency: if the most frequent letter of the ciphertext coincides with the one expected for the language (E, in English), that is a sign of transposition, not substitution. What isolated-letter frequency does not reveal, on its own, is the reading order of the columns: for that, other clues are needed, such as frequent digraphs and trigraphs split in half by the grid, or trying various column widths. Repeating the transposition several times, with different keys (**double** or multiple transposition), considerably hinders manual reconstruction, although it remains vulnerable to modern computational attacks.</span>
<span id="cb13-395"><a href="#cb13-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-396"><a href="#cb13-396" aria-hidden="true" tabindex="-1"></a>Historically, the combination of substitution and transposition, each weak in isolation but strong when combined, is the principle that gives rise to the modern concepts of **confusion** and **diffusion**, introduced by Shannon and central to the design of the modern block ciphers studied in the next chapter.</span>
<span id="cb13-397"><a href="#cb13-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-398"><a href="#cb13-398" aria-hidden="true" tabindex="-1"></a><span class="fu">## Chapter Summary {#sec-01-sintese}</span></span>
<span id="cb13-399"><a href="#cb13-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-400"><a href="#cb13-400" aria-hidden="true" tabindex="-1"></a>This chapter established the vocabulary and fundamental principles that run through the whole discipline of cryptography:</span>
<span id="cb13-401"><a href="#cb13-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-402"><a href="#cb13-402" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>A symmetric cryptographic system is defined by its five components, plaintext, encryption algorithm, secret key, ciphertext and decryption algorithm, related by $Y = E(K, X)$ and $X = D(K, Y)$</span>
<span id="cb13-403"><a href="#cb13-403" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Kerckhoffs's principle** establishes that the security of a cipher must depend solely on the secrecy of the key, never on the secrecy of the algorithm</span>
<span id="cb13-404"><a href="#cb13-404" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>An attacker has two general strategies available: **brute force** (exhaustively testing the key space) and **cryptanalysis** (exploiting additional information to deduce the key without testing it exhaustively)</span>
<span id="cb13-405"><a href="#cb13-405" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Substitution ciphers** (Caesar, monoalphabetic, Playfair, Vigenère) replace plaintext symbols with other symbols, with decreasing, but never entirely eliminated, vulnerability to frequency-analysis attacks</span>
<span id="cb13-406"><a href="#cb13-406" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>The **Vernam cipher** generalises Vigenère with XOR and a much longer key, mitigating but not eliminating the problem of a repeating key; the **One-Time Pad** eliminates it completely, being the only classical cipher that is mathematically unbreakable, at the cost of key-management requirements that are impractical in most real-world scenarios</span>
<span id="cb13-407"><a href="#cb13-407" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Enigma** mechanised the polyalphabetic principle on an industrial scale, replacing Vigenère's short keyword with electromechanical rotors; it fell not to frequency analysis, but to a structural design flaw combined with probable words ("*cribs*") tested at scale by the Bombe</span>
<span id="cb13-408"><a href="#cb13-408" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Transposition ciphers** reorder the symbols of the plaintext without changing their identity, and form the historical basis of the modern concepts of confusion and diffusion</span>
<span id="cb13-409"><a href="#cb13-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-410"><a href="#cb13-410" aria-hidden="true" tabindex="-1"></a><span class="fu">## Discussion Question {#sec-01-reflexao}</span></span>
<span id="cb13-411"><a href="#cb13-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-412"><a href="#cb13-412" aria-hidden="true" tabindex="-1"></a>Why is it that the One-Time Pad, despite being mathematically unbreakable, is not the universal solution to every problem of secure communication? What other problem, just as hard as that of the message itself, does its use end up introducing?</span>
<span id="cb13-413"><a href="#cb13-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-414"><a href="#cb13-414" aria-hidden="true" tabindex="-1"></a><span class="fu">## References {#sec-01-referencias .unnumbered}</span></span>
<span id="cb13-415"><a href="#cb13-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-416"><a href="#cb13-416" aria-hidden="true" tabindex="-1"></a>::: {#refs}</span>
<span id="cb13-417"><a href="#cb13-417" aria-hidden="true" tabindex="-1"></a>:::</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Cryptography — Cybersecurity, UTAD</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>